### ISSUE TITLE
Better cookie support

### ISSUE THREAD

**Issue by matt-riemer** [code-and-effect/effective_datatables#101]
Hey @Nerian 

Mind checking out version 4.4.2?

After your cookie changes, I ran into the issue where just Google Chrome would not have the "_effective_dt" cookie set when visiting an address like "http://localhost:3000/somewhere"

Firefox would do it, but not Chrome.

I researched and discovered this was a TLD LENGTH cookie issue.

I've extracted some EffectiveDatatables config variables, and better auto-detecting the correct TLD length.

Does this break anything for you? :)

**Comment by matt-riemer** [comment]
https://github.com/code-and-effect/effective_datatables/commit/3a355525070e93fcaf6f267b7cb23f59a411ea84

**Comment by Nerian** [comment]
Hi!

Sure thing.

I added to the Gemfile:
```
gem 'effective_datatables', github: "code-and-effect/effective_datatables", branch: 'master'
```

I got this error when I launched:

➜  eucalipto-app git:(master) ✗  rails s
=> Booting Puma
=> Rails 5.2.2.1 application starting in development
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	75: from bin/rails:4:in `<main>'
	74: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	73: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	72: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	71: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	70: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	69: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	68: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	67: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	66: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/commands.rb:18:in `<main>'
	65: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/command.rb:46:in `invoke'
	64: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/command/base.rb:65:in `perform'
	63: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	62: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	61: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	60: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	59: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	58: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	57: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:51:in `start'
	56: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	55: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	54: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
	53: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	52: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	51: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	50: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	49: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	48: from config.ru:in `<main>'
	47: from config.ru:in `new'
	46: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	45: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	44: from config.ru:3:in `block in <main>'
	43: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
	42: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
	41: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	40: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
	39: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	38: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	37: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	36: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	35: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	34: from /Users/Nerian/projects/eucalipto-app/config/environment.rb:5:in `<main>'
	33: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
	32: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	31: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	30: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	29: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	28: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `call'
	27: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:347:in `each'
	26: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	25: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	24: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:415:in `call'
	23: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	22: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
	21: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	20: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	19: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	18: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	17: from /Users/Nerian/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	16: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	15: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
	14: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	13: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
	12: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
	11: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	10: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
	 9: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
	 8: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
	 7: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
	 6: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	 5: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
	 4: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 3: from /Users/Nerian/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 2: from /Users/Nerian/projects/eucalipto-app/config/initializers/effective_datatables.rb:1:in `<main>'
	 1: from /Users/Nerian/.rvm/gems/ruby-2.6.2/bundler/gems/effective_datatables-6903d23444b3/lib/effective_datatables.rb:23:in `setup'
/Users/Nerian/projects/eucalipto-app/config/initializers/effective_datatables.rb:37:in `block in <main>': undefined method `max_cookie_size=' for EffectiveDatatables:Module (NoMethodError)
Did you mean?  cookie_max_size=
```

I simply needed to remove the old config in the initializer:

```
// Remove this
config.max_cookie_size = 2000
// Ad this
config.cookie_max_size = 2000
```

Then it works flawless. Nice job!

You may want to add some message when upgrading the Gem, letting the users know about the config change. It will crash to everybody who is upgrading, so a message will cut some support time :)

**Comment by matt-riemer** [comment]
Ack, I specifically added an alias_method for this one!

Thanks for the quick check anyway, glad this works! mostly. :)
