### ISSUE TITLE
Just a few questions..

### ISSUE THREAD

**Issue by JerrodCarpenter** [code-and-effect/effective_datatables#102]
First off, great gem. The API is really intuitive and fun to use. I just have a few questions on how to do some things: 
1. I'm having trouble implementing the datatable in an asynchronous fashion. The use case is this, I have a modal that has a datatable within and since it's not displayed right away, I'd like it to load asynchronously to improve the page load time. Unfortunately, it seems as though this isn't possible. 
2. Second, are there any thoughts to providing UUID support?

I'm happy to contribute in these areas if you have an idea of how you'd like to achieve these features.

**Comment by matt-riemer** [comment]
Hey great questions!

1. If you load the datatable after your initial page load, you can fire one of the following events to have it initialize:

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/initialize.js.coffee#L184

`jQuery ready()`

or

`$(document).trigger('turbolinks:load')`

or

`$(document).trigger('effective-datatables:initialize')`

or more targetted,

`$('.somediv').trigger('effective-datatables:initialize')`


One of those will work!


I have not thought about adding UUID support, but seems like a good idea / approachable.

Are you up for digging into it?

**Comment by JerrodCarpenter** [comment]
Thanks for the quick response!

hmmm, I tried that third option (`$(document).trigger('effective-datatables:initialize')`). It seems to chop off some of the form fields in the top right and the search boxes over the columns. Additionally, some of the data isn't being printed within the columns.

<img width="630" alt="Screen Shot 2019-03-26 at 12 28 43 PM" src="https://user-images.githubusercontent.com/4128301/55019439-e70ab880-4fc2-11e9-8c23-1e83ac0f24e8.png">

**Comment by JerrodCarpenter** [comment]
Still struggling with this, I'll try to provide more information on how I'm attempting to achieve this.

When the view loads, this javascript is kicking off:
```javascript
    fetch(this.data.get('url'), { credentials: 'same-origin', headers })
      .then(response => response.text())
      .then((html) => {
        this.element.innerHTML = html;
      });
  $(document).trigger('effective-datatables:initialize')
```

The html being returned here is a partial. This is what the partial looks like:
```ruby
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3 Things
      = render_datatable(@things, input_js: { deferRender: true, lengthMenu: [10, 50, 100, 500, 1000] })
```

And the controller looks like this:
```ruby
  # Renders the user things datatable.
  def things
    @things = ThingsDatatable.new(user_id: User.find_by!(name: params[:name]).id)
    render partial: 'users/things'
  end
```

And it does seem to render the first ten rows, but the search, sort, pagination, and column picker form buttons do not render. Do you have an example of how to do this?

**Comment by matt-riemer** [comment]
1.) I think that `$(document).trigger` has to be done inside your `.then((html) => ` after you assign all the html to your element.

It needs to run after your assign the html to your new element.  

2.) I'm not sure what `input_js { deferRender: true }` does...you shouldn't need it tho.  When effective_datatables renders a table for the first time, all the information is in place and drawn.  It only makes a second request to the server once you sort/search/paginate.

**Comment by matt-riemer** [comment]
Seems weird it would chop off those form fields and such.  I use the datatables.net plugin Responsive to handle tables too big for the viewport. Might be something weird going on there.

Are you having any javascript errors?

Try deleting your "_effective_dt" cookie and trying again.

**Comment by JerrodCarpenter** [comment]
Okay, I've moved the trigger where you suggested and removed the `deferRender`, still the same results. As for the size, the datatable loads fine when I initialize it within the parent controller/view cycle. I'm not seeing any javascript errors and it looks like this cookie is not being created as far as I can tell.

I'm still fuzzy on how `effective_datatables` knows which controller action to use to grab more rows if I'm not explicitly setting it.

**Comment by matt-riemer** [comment]
Yea great question.

The controller is always `Effective::DatatablesController#show`

https://github.com/code-and-effect/effective_datatables/blob/master/app/controllers/effective/datatables_controller.rb#L6

**Comment by JerrodCarpenter** [comment]
> As for the display...I'm not really sure...do you have Twitter Bootstrap 4 installed and working in your layout?

No, and I should have mentioned this, but I'm using your Bootstrap 3 branch.

**Comment by JerrodCarpenter** [comment]
So I loaded the same datatable via the parent controller and one asynchronously, the one loaded via the controller loaded correctly. What's interesting is, when I clicked on some of the form elements on the correctly loaded one, the asynchronous table gets loaded completely and starts working correctly. This leads me to believe that the javascript isn't initializing on the element correctly. I'm still doing some investigation.

**Comment by matt-riemer** [comment]
I think you mayb need to make sure the datatable is visible before calling initialize on it!

Hope that helps

**Comment by JerrodCarpenter** [comment]
I've ensured this by setting a breakpoint in my browser and triggering the event only after the datatable is visible. Still nothing. Notably, the element structure of the table is much more different than the one loaded from the controller.

From controller:
<img width="595" alt="Screen Shot 2019-04-02 at 7 51 02 AM" src="https://user-images.githubusercontent.com/4128301/55403792-39e0f480-551c-11e9-8536-5021377708b7.png">

From AJAX:
<img width="574" alt="Screen Shot 2019-04-02 at 7 51 28 AM" src="https://user-images.githubusercontent.com/4128301/55403810-3fd6d580-551c-11e9-98b5-a74f8d5878f8.png">

**Comment by matt-riemer** [comment]
Not really sure how to help out here...

Try to simplify and check all your assumptions!

Good luck!

**Comment by JerrodCarpenter** [comment]
@matt-riemer I'm just trying to understand if this is a defect in the gem or my implementation, do you have any examples of this working asynchronously?

**Comment by matt-riemer** [comment]
sorry I don't have a demo app, I probably should get one set up :/

**Comment by JerrodCarpenter** [comment]
Alright, I'll keep looking into this to see if it's possible.

**Comment by matt-riemer** [comment]
@JerrodCarpenter The internet delivers!

https://effective-datatables-demo.herokuapp.com/
https://github.com/code-and-effect/effective_datatables_demo

I also ran into an InvalidAuthenticityToken issue while building out a brand new rails 5.2 site from scratch. (It's been awhile) and ended up publishing effective_datatables version 4.4.4 and 3.5.4.

Cheers mate :)

**Comment by JerrodCarpenter** [comment]
I appreciate the example, which datatable is being loaded via Ajax on the page?

**Comment by matt-riemer** [comment]
man, I would just never write it that way. why not just render them directly?

I dunno...i don't see why it wouldn't work tho. Once you load all your html, just fire like a jquery ready event or turbolinks load or datatables:initialize

**Comment by JerrodCarpenter** [comment]
> man, I would just never write it that way. why not just render them directly?

Hah, well we have a number of forms that load these data tables in the back ground (they live in hidden modals on page load). The benefit of loading them in the background is the page loads much quicker because there's less back and forth between the database. I've looked at maybe just taking this hit on that, it looks like each invocation of an `effective_datatables` object is just 3 SQL queries, which isn't too terrible.

I've tried kicking off these javascript events, but it doesn't seem like they make a difference (I could be doing something wrong). I keep thinking it's related to how the gem is deciding which controller to hit, but mostly that's because I'm not sure how that's working.

This is somewhat unrelated to my asynchronous issues, but when I was digging into it, I noticed that the data tables are given IDs that I believe `effective_datatables` uses. Do you think there could be a  clash if I wanted two data tables of the same type (but with different columns auto loaded)? I came up with a system to pass through attributes to the datatable object so that I could control which columns where marked as visible at invocation. Would the better way to do this to be create a different datatable class against the same backing table, but with different configuration?

That all being said, I appreciate your time and I'm sure I've been a pain. I really appreciate the slick DSL this gem provides so I'm going to keep digging into this.

**Comment by matt-riemer** [comment]
I don't think there would be a clash. You can definitely create separate instances of the same datatable class on the same page.

I'd configure them with something like
```ruby
col :thing, visible: false
```
or you could do
```ruby
@datatable = PostsDatatable.new(visibility_mode: 'full')`

col :thing, visible: (attributes[:visibility_mode] == 'full')
```

**Comment by JerrodCarpenter** [comment]
Hah, yeah, that's pretty much what I was doing.
