### ISSUE TITLE
Showing the date

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#105]
Hi,

I have got this filter:
```ruby
filters do
  filter :from, Date.current.beginning_of_week, required: true
  filter :to, Date.current.end_of_week, required: true
end
```

And it shows with the dates empty, even if the filters actually do apply the relevant dates.

<img width="1395" alt="what i got" src="https://user-images.githubusercontent.com/259568/56426820-d7c51500-62b9-11e9-968d-0fb5a8a1a786.png">

But I would the UI to show the date, because the user needs to know. Like this:

<img width="1394" alt="what i got" src="https://user-images.githubusercontent.com/259568/56426897-2ecaea00-62ba-11e9-902c-b6ddf4ab4e40.png">

Is there an option to do that?

Thanks!

**Comment by Nerian** [comment]
I ended up doing this:

```ruby
filters do
  filter :from, Date.current.beginning_of_week, input_js: { defaultDate: Date.current.beginning_of_week }
  filter :to, Date.current.end_of_week, input_js: { defaultDate: Date.current.end_of_week }
end
```

Works good 🎉

**Comment by matt-riemer** [comment]
I ended up fixing this. Please upgrade to effective_bootstrap 0.4.5

datatables was correctly passing `:value` to the input, but the input wasn't doing the right thing with it! :)

I'm using a datatable like this:

```
class ThingsDatatable < Effective::Datatable
  filters do
    filter :start_date, Time.zone.now.to_date, required: true, as: :date
    filter :end_date, nil, as: :date
  end

  datatable do
    col :created_at
    col :updated_at,
    col :id

    col :title
    col :date

    actions_col
  end

  collection do
    range = (filters[:start_date]..filters[:end_date]&.end_of_day)
    Thing.all.where(date: range)
  end
end
```

and it's doing the right thing now!

**Comment by Nerian** [comment]
Awesome! We are getting lots of things done today :)

It works perfectly well. Thanks.
