### ISSUE TITLE
Bug in filters

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#110]
Hi,

I just noticed this new behaviour. I have this filter in a datatable:

```ruby
filters do
    filter :client_id, nil, as: :select, collection: Client.all, placeholder: t('general.client')
    filter :solicitor_id, nil, as: :select, collection: Solicitor.joins(:expedients).all, placeholder: t('general.solicitor')
    filter :lawyer_id, nil, as: :select, collection: Lawyer.all, placeholder: t('general.lawyer')
    filter :legal_classification_id, nil, as: :select, collection: LegalClassification.all, placeholder: t('general.legal_classification')
    filter :procedure_type_id, nil, as: :select, collection: ProcedureType.all, placeholder: t('general.procedure_type')
    filter :special, nil, as: :select, collection: special_collection, placeholder: t('general.special')
    filter :current_macro_id, nil, as: :select, collection: macro_collection, placeholder: t('general.doing')
  end
```

This is what I get now:

<img width="637" alt="Captura de pantalla 2019-04-24 a las 8 40 44" src="https://user-images.githubusercontent.com/259568/56637845-ec642d00-666c-11e9-803a-3674ac7a7868.png">

Notice that the `solicitor` filter contains the parameters passed to the input instead of the option from the collection.

I tried a few things and I noticed that this behaviour only happens when I am using `.joins(:expedients).all` and the resulting collection is empty. So for example `Lawyer.joins(:expedients).all` renders good, because there are some lawyer with some expedients; but `LegalClassification.joins(:expedients).all` renders the buggy version. 

I tracked down the commit that introduced this bug. This was working correctly at 7b305b12bb0c1fb461fd3cb7ee0b1d7567f23c8a but started working incorrectly at 25db35ff37e9e78095b521cb8fb476be2ba982ea.

**Comment by matt-riemer** [comment]
Yea, I see what was going on here

I was checking for `collection.present?`.  Doh!  I've changed it now to be `if [:select, :radios, :checks].include?(as)` which is probably the better check.

Thanks, sorry for this bug :)

Wish this gem had an elaborate test suite, but it probably wouldn't have caught this anyway :)

This has been fixed in `effective_datatables 4.5.1`
