### ISSUE TITLE
Bug:  Order is not working

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#112]
Hi there!

The `order` method is not working. It is ignored by datatables and the first column is always taken as the 'order' column. Clicking on the column to force a sort does work.

I tracked down the commit in which `order` starts to no longer work as intended. This is it:

https://github.com/code-and-effect/effective_datatables/commit/a020c3fa8c580caadf39dbfb7aa154c4dee48f88

It works on the previous commit:  https://github.com/code-and-effect/effective_datatables/commit/b7edcce0999650f051edc4eb342d57d3d83882c4

This is from release 4.3.5. The bug is present in all releases since that one.

I keep digging on why this happens I think this piece of code here is relevant:

https://github.com/code-and-effect/effective_datatables/commit/a020c3fa8c580caadf39dbfb7aa154c4dee48f88#diff-9956388416cac79800d0f9002cf672c9R147

Shouldn't that code include check of `state[:order_name]`? Because otherwise is never checked I believe.

If I include it there it does work on my app. Did I fix it or is it something else?

This is what I did:  

https://github.com/code-and-effect/effective_datatables/pull/113/files

**Comment by matt-riemer** [comment]
You are a true internet hero. Thanks @Nerian !

Sorry you had to dig through all that code :)

Merged and released as effective_datatables 4.5.7

**Comment by Nerian** [comment]
Awesome, thanks! 💇‍♂
