### ISSUE TITLE
Conflict with Kaminari

### ISSUE THREAD

**Issue by RyanQuey** [code-and-effect/effective_datatables#115]
Since this gem requires effective_bootstrap in the Gemfile and effective_bootstrap defines a `paginate` helper, I'm running into trouble since it overwrites the helper Kaminari defines. 

Any suggestions for how to use effective_datatables with Kaminari?

**Comment by matt-riemer** [comment]
Hey please upgrade to

effective_bootstrap 0.6.2

I renamed the method so that kaminari `paginate` would take precedence.
