### ISSUE TITLE
Rails 5 secret_key_base NoMethodError

### ISSUE THREAD

**Issue by dgbtech** [code-and-effect/effective_datatables#117]
I am using effective datatables -v4.7.12, after devise login, when datatable loads I get the error:
`undefined method "secret_key_base" for #<Appname::Application:0x0000000003926cd0>`

Error comes from lib/effective_datatables.rb:
`82 ActiveSupport::MessageEncryptor.new(Rails.application.secret_key_base.to_s.first(32))`

I can access secret using:
`Rails.application.secrets.secret_key_base`

¿Is there a version compatibility problem (Rails 5.0.7.2) or my config problem?. I have in mind to use pundit but for now I've:
`config.authorization_method = true`

TIA

**Comment by matt-riemer** [comment]
Hey

Give effective_datatables 4.7.13 a shot.

Here's the commit I ended up with:

https://github.com/code-and-effect/effective_datatables/commit/0d0b2b721fd956e69d093800d9512052722631e0

Weird that your app doesn't respond to Rails.application.secret_key_base, all mine do :)

**Comment by dgbtech** [comment]
Thank you for your fast answer and changes, but I keep having problems with Rails 5.0.7.2 and I cant update Rails because other dependencies, problem is now with **form_with in effective_bootstrap**:

```
NoMethodError at /

undefined method `form_with' for #<#<Class:0x000000000453e338>:0x0000000004553260>
Did you mean?  form_tag

effective_bootstrap (0.6.10) app/helpers/effective_form_builder_helper.rb
50 form_with(**options.merge(builder: Effective::FormBuilder), &block)
```

Dont know if more people with this version is having this issues.TIA
