### ISSUE TITLE
Merge records of two tables

### ISSUE THREAD

**Issue by rohangrg** [code-and-effect/effective_datatables#118]
```
class Teacher < ActiveRecord    // contains id and name
  has_many :students
end 
class Student < ActiveRecord    //contains id,name and teacher_id
  belongs_to  :teacher 
end
```

**Now what I want to do is :**  
 scope = Teacher.joins("LEFT OUTER JOIN students ON students.teacher_id = teachers.id")

I want to make a datatable containing following columns
TeacherID  , TeacherName , Student Name 

**Problem :** 
How to access student name for individual row, 
For Eg, Teacher1 have 2 students 
```
col :student_name do |teacher|
  teacher.students      //this will give all students , but i want to access the current student only
 end
```

**Note there are few teachers who don't have any students, so I just want to print the id and name of that teacher, and for rest of the teachers there will be multiple rows for each student they have.**

**Comment by matt-riemer** [comment]
Would something like this work?

```
class StudentsDatatable < Effective::Datatable

  datatable do
    col :name
    col :teacher
    col :teacher_name do |student|
      student.teacher.name 
    end
  end

  collection do
    Student.where(teacher: teacher)
  end

  def teacher
    @teacher ||= Teacher.find(attributes[:teacher_id])
  end

end
```

```
@datatable = StudentsDatatable.new(teacher_id: 3)
```

**Comment by rohangrg** [comment]
I guess this will only work for teachers who have atleast one student..what if a teacher have no student? I still want to print teacher id and teacher name..

Thanks for early response by the way..

**Comment by matt-riemer** [comment]
If teacher `has_many :students`, it should just work out of the box in Datatables. With all of the students being displayed in one column.

Not quite you want. I realize.



```ruby
class TeachersDatatable < Effective::Datatable

  datatable do
    col :name
    col :students
  end

  collection do
    Teacher.all
  end

end
```

If you instead had a teacher `has_many :students, through: :teachings` you could make a datatable for the teachings / job table. And then you'd have the Teacher/Student join combinations done for you by rails

```ruby
class Teaching
  belongs_to :teacher
  belongs_to :student
end
```

```ruby
class TeachingsDatatable < Effective::Datatable

  datatable do
    col :teacher
    col :student
  end

  collection do
    Teaching.all
  end

end
```

**Comment by rohangrg** [comment]
Thanks  @matt-riemer
