### ISSUE TITLE
action_cols order

### ISSUE THREAD

**Issue by rohangrg** [code-and-effect/effective_datatables#121]
Hi,

Just a simple question. Is there any way to change the order of actions in the action_cols?

Thanks !!

**Comment by rohangrg** [comment]
@matt-riemer ??

**Comment by matt-riemer** [comment]
Hey sorry for the long response time here :)

Yup! there sure is.

I think it's either

`actions_col(actions: [:new, :edit, :show])`

or 

`actions_col(new: true, edit: true, show: false)`

and it should keep the order as you define them

**Comment by rohangrg** [comment]
Thanks @matt-riemer  !!!!!

**Comment by rohangrg** [comment]
Hey @matt-riemer ,
I tried using the above mentioned methods by you , but non of them worked for me ,
It was even showing error in the first one.
Thanks
