### ISSUE TITLE
add  style to row

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#122]
Hi!

I would like to present the user with table of comments. And these comments should have different colours, that depends on what the user has configured.

So I would like to add a background-color to certain rows, depending on the value of the entry.

So adding to the `tr` something like this `style="background-color: 'ffeedd'"`.

I see there is an option to add a class to the column. `col_class: 'col-green'`. I was wondering if it would be possible to add a class/style to rows.

Thanks!

**Comment by Nerian** [comment]
Here is what is on my mind regarding how feature could look like:

```ruby
class CommentsDatatable < Effective::Datatable
  datatable do   
    col :something   
    col :somethang   
  end

# `class_names` and `style` accept a single argument.
  row_options do
    class_names 'this-is-a-class'
    style 'background-color: green;'
  end

# `class_names` and `style` accept a block, which is passed with the entry.
  row_options do
    class_names do |entry|
      if entry.whatever
        'class-type-1'
      else
        'class-type-2'
      end
    end

    style do |entry|
      "background-color: #{{entry.color}};"
    end
  end

  collection do
    Comment.all
  end  
end

```

**Comment by Nerian** [comment]
I believe we can insert `class` and `style`  using:

https://datatables.net/reference/option/createdRow

**Comment by matt-riemer** [comment]
Nice!

I think this could be fairly involved, but I'm open to looking into it.

Can you not just use css for this? :)

**Comment by Nerian** [comment]
The reason I can't use css is that the colour that should be applied to each row depends on the object of the row. So it's not a style that depends on the placement, or order, but is an attribute that depends on the values of the entity. 

So I need a way to either add a data attribute to the row, which I can then use with some javascript to set the color, or to be able to style the row directly.

Another possibility I have been thinking is to add a new column that contains the colour hex. And hide the column. And then via javascript I would navigate the table and find the hex color code and then apply it to the row. I would need to be able to listen to update events so that when the table is changed this code is ran again. Do effective datatable raise events?

**Comment by matt-riemer** [comment]
Sorry I never really came back to this.

Sounds efforty and I'm not really interested in it. Sorry Nerian :(

**Comment by Nerian** [comment]
No problem. I just implemented the table as a regular table; no datatable. So far there is no need for advance sorting or filters.

Thanks!
