### ISSUE TITLE
Clear Search  

### ISSUE THREAD

**Issue by rohangrg** [code-and-effect/effective_datatables#126]
Hey,
Is there a way to clear all the search inputs using buttons,

I tried some of the stackoverflow answers, but none of them worked.
https://stackoverflow.com/questions/27402208/remove-search-filter-on-datatable

**Comment by matt-riemer** [comment]
Heyo!

Yes...that's what the little "Reset" button next to the Bulk Actions does.

Which, you can see the code for here:

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/reset.js.coffee
