### ISSUE TITLE
DataTable error: expected attributes to be present

### ISSUE THREAD

**Issue by eleos** [code-and-effect/effective_datatables#128]
As of version 4.7.0 I get this error when changes the page in the datatable.

**Comment by matt-riemer** [comment]
Heyo,

Around 4.7.0 is when I moved from storing the attributes in a cookie to an encrypted payload.

Can you upgrade all the way to 4.7.17 (latest?) and do you still run into any problems?

Try clearing your cookies and see if that has any effect :)

Cheers

**Comment by eleos** [comment]
Same problems. Am debugging right now. I came from a 4.7.17 upgrade, which failed with the same error.

Tried:
- Erasing cookies
- Checking different versions

What is found out so far:
- The params[:attribute] is not being set.

This only happens in my windows environment. My linux environment does work.

**Comment by eleos** [comment]
Fixed! Had to disable the assets precompile to load the correct assets to add the attributes tag.

**Comment by matt-riemer** [comment]
This is a great fix, thank you eleos!
