### ISSUE TITLE
Bootstrap3 filters always required

### ISSUE THREAD

**Issue by srodney86** [code-and-effect/effective_datatables#129]
Hello,
Really great gem, thank you very much.

I am using the Bootstrap3 branch and find that the filters select fields are always have the required attribute. If I switch to the master branch then they work as expected.
I am using the latest versions.

The same can be seen if I use the demo and switch to using bootstrap 3 and switching to bootstrap 3 branch.

Any idea why?

Can filters be not required on the Bootstrap3 branch?

Many thanks for any input.

**Comment by matt-riemer** [comment]
As you wish! :)

Upgrade to effective_datatables 3.7.6 and the filter fields are now `required: false` by default

And you can pass `required: true` if you want it to be required too.

Thanks for using this gem!
