### ISSUE TITLE
charts processing error on new page

### ISSUE THREAD

**Issue by jeremydubansky** [code-and-effect/effective_datatables#130]
Hello

I am getting this error when trying to display a chart and go to a new page in the datatable. seems like the chart is trying to load before the data can be generated yet even with static arrays it still errors out.

`initialize.source.js.coffee:134 Uncaught TypeError: google.visualization[data.type] is not a constructor
    at HTMLDivElement.<anonymous> (initialize.source.js.coffee:134)
    at Function.each (jquery3.source.js:367)
    at jQuery.fn.init.each (jquery3.source.js:202)
    at Object.<anonymous> (initialize.source.js.coffee:133)
    at Function.each (jquery3.source.js:373)
    at drawCharts (initialize.source.js.coffee:132)
    at jQuery.fn.init.drawCallback (initialize.source.js.coffee:103)
    at jquery.dataTables.source.js:6636
    at Function.map (jquery3.source.js:456)
    at _fnCallbackFire (jquery.dataTables.source.js:6635)`
<img width="326" alt="Screen Shot 2020-03-06 at 10 51 21 PM" src="https://user-images.githubusercontent.com/7358437/76136980-52e00880-5ffd-11ea-9ce8-a5d303ec33d8.png">
<img width="1594" alt="Screen Shot 2020-03-06 at 10 51 30 PM" src="https://user-images.githubusercontent.com/7358437/76136982-55daf900-5ffd-11ea-9a96-86880d804347.png">

**Comment by matt-riemer** [comment]
Heyo

https://developers.google.com/chart/interactive/docs/quick_start

Add

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

into your page's javascript is the fix here :)

Cheers

**Comment by jeremydubansky** [comment]
I can check when I get home but I'm pretty sure I had that in the <head> for my application and it was still failing when I went to a new page in the table. The initial load is just fine, only erroring out when I change pages within the table.

**Comment by matt-riemer** [comment]
https://effective-datatables-demo.herokuapp.com/charts

Check that out for a working demo

Code:

https://github.com/code-and-effect/effective_datatables_demo

**Comment by matt-riemer** [comment]
Could very well be some javascript gotcha still tho :)

**Comment by jeremydubansky** [comment]
It does the same thing when you add charts to the demo 

<img width="1421" alt="Screen Shot 2020-03-09 at 2 27 17 PM" src="https://user-images.githubusercontent.com/7358437/76249917-3ec12480-6212-11ea-961c-0e94d9a15450.png">
<img width="1025" alt="Screen Shot 2020-03-09 at 2 27 31 PM" src="https://user-images.githubusercontent.com/7358437/76249918-3f59bb00-6212-11ea-8e2c-9d5129e295a1.png">

**Comment by matt-riemer** [comment]
Aaah, yea it is too. I can reproduce.

Busted charts stuff! Why you no work!? ;)

Gimme a few here, fix incoming.

**Comment by jeremydubansky** [comment]
im not the only one!!! i was blaming myself for a few hours haha. Thanks for looking at this so quickly!

**Comment by matt-riemer** [comment]
Heyo

Give 4.7.20 a shot. I think it should work without javascript errors now!

Here's what I changed:

https://github.com/code-and-effect/effective_datatables/commit/72af29cffe646551aa6d9464b706b407d0c1c892

and, FYI

https://github.com/code-and-effect/effective_datatables_demo/commit/e6d11fcd66b47ea70ad3c6f4a8e8fc5d7f412a96

Thanks!

**Comment by jeremydubansky** [comment]
the demo looks like it is working properly! I can test my other code at home. Thanks for the fast turn around on this!
