### ISSUE TITLE
SVG file not found in production

### ISSUE THREAD

**Issue by jeremydubansky** [code-and-effect/effective_datatables#131]
Hello,
I cant seem to find any differences in my code for local vs prod that would cause this but I'm getting this error in production. It looks like it is only on filters and I am sure the fix is obvious to someone else. 

<img width="1314" alt="Screen Shot 2020-03-10 at 10 52 39 AM" src="https://user-images.githubusercontent.com/7358437/76331802-95d00380-62bd-11ea-8084-b28c2d8762aa.png">

**Comment by matt-riemer** [comment]
Hmm....must be some kind of svg loading issue.

All those svgs come from effective_bootstrap gem, which should be a dependendy of datatables here.

I've got them running in production on many sites without anything special.

What rails version are you on?

**Comment by jeremydubansky** [comment]
Here is my gemfile, also I am a bit newer to rails so the issue could VERY well be me. I also had some other datatable gems in here but took those out once I found this.

`ruby '2.6.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.3'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
# gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'mini_racer', platforms: :ruby
gem 'jquery-rails'
gem 'sprockets-rails', '~> 3.1', '>= 3.1.1'
gem 'sass-rails'
gem 'bootstrap'
gem 'devise'
gem 'bootstrap_form'
gem 'popper_js', '~> 1.9', '>= 1.9.9'
gem 'haml-rails'            # or try using gem 'hamlit-rails'
gem 'effective_datatables'
gem 'kaminari'
gem 'font-awesome-sass'
gem 'ipaddress'
gem 'grape'
gem 'mailgun-ruby', '~>1.1.6'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'`

**Comment by matt-riemer** [comment]
I've been scratching my head a little bit about this:

1.) I think the fix is to add `gem "effective_bootstrap"` to your gemfile.   It is a dependency of datatables, but maybe the initializer in that gem is only run when it's defined as a top level gem. I'll have to document this better

2.) I have an example rails 6 app, and live demo up on the internet if you wanna poke around.

It's working with latest effective_datatables, effective_bootstrap, etc. And has a working calendar icon :)

https://github.com/code-and-effect/effective_website/

and

https://effective-website-demo.herokuapp.com

**Comment by jeremydubansky** [comment]
I'll have to try that tonight and see if it changes anything I thought it was something to do with the asset pipeline.

**Comment by jeremydubansky** [comment]
I was able to upgrade to 2.6.5 and I'm still having the issue. I wonder if it has something to do with how it accesses the asset pipeline (again I'm fairly new to this). It is also adding this text `' data-total-records='4028' id='hosts_datatable-323990943659'>` right below the filter, not sure if it is related at all but the response of the collection is fairly large, maybe 200 pages of 25 rows.

<img width="1361" alt="Screen Shot 2020-03-10 at 9 19 22 PM" src="https://user-images.githubusercontent.com/7358437/76375901-f0e11500-6314-11ea-8655-bb04cb1ffc88.png">

**Comment by jeremydubansky** [comment]
While i think my issue is more on the asset pipeline area because it works on local, i wonder if using "Effective Form With" is a better route. Can these be used with filters in Effective Datatables? I shall try!

**Comment by matt-riemer** [comment]
Try using that effective_bootstrap gem directly in your gemfile

Then just, in any view, use `= icon('calendar')` see if that works on development vs production.

asset pipeline can be a pain in the butt :)

**Comment by jeremydubansky** [comment]
seems like it might not just be a SVG issue but an issue with the filters all together, its not even calling the ajax to repopulate.

**Comment by matt-riemer** [comment]
do you have a repo I could check out? :)

**Comment by jeremydubansky** [comment]
unfortunately not, I am using AWS elastic beanstalk and wondering if it is some sort of puma/buffer issue of some sort. The charts work just fine if there is no filter

**Comment by jeremydubansky** [comment]
FIXED!!!
I had to add the following lines to production.rb and now everything is loading correctly!

config.public_file_server.enabled = true
config.assets.compile = true
