### ISSUE TITLE
strip search value on scopes

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#132]
Hi,

Let's say I define a table with a simple column that is a string.

```ruby
class ExpedientsDatatable < Effective::Datatable
     datatable do
       col :original_contract
     end
   end
```

It works fine when user inputs a string without surrounding whitespace, but when the user is copy pasting something then the search text will include whitespace. Example:

```
SELECT "expedients".* FROM "expedients" WHERE ("expedients"."original_contract" ILIKE '%   50016736590901 %') ORDER BY "expedients"."original_contract"='' ASC, "expedients"."original_contract" ASC NULLS LAST LIMIT $1 OFFSET $2
```

And the query results in nothing. Furthermore, if the user then tries to remove the whitespace datatable doesn't try to search again. 

So far I am doing:
```
col(:original_contract, label: t('general.original_contract')).search do |collection, term, column, sql_column|
      collection.where("expedients.original_contract ILIKE ?", "%#{term.strip}%")
    end
```

That `strip` fixers the issue, but seems like a lot of boilerplate; and this is probably a common problem.
 
I am wondering if you could just add a `strip` call to the default search query? Or maybe add an option to `strip` it? What do you think?

Thanks!

**Comment by matt-riemer** [comment]
Hey thanks for the great write up of the description. Appreciate it.

K, done! :)

Check out effective_datatables 4.7.21

https://github.com/code-and-effect/effective_datatables/commit/49c95738818dd7e7a577a1038e45377bbf50a0f3


1.) All search terms will be trimed by default.  But you can now search for something like `" something "` with the quotes if you want to include the leading/trailing spaces

**Comment by Nerian** [comment]
Oh forgot to answer. Worked like a charm! Thx!
