### ISSUE TITLE
Undefined method authorize!

### ISSUE THREAD

**Issue by nekapoor** [code-and-effect/effective_datatables#133]
Hello!

I'm running into this issue: 
```
undefined method `authorize!' for #<Admin::UsersController:0x00007fa0f494f010>
Did you mean?  authorize
```

*This issue occurs whenever I include `actions_col`in my datatable block. If I take this out, the table will render.*

In `effective_datatables.rb`, I've tried a number of things: 

```
  config.authorization_method = :my_authorization_method
  def my_authorization_method(resource, action)
    true
  end
```

and 

`config.authorization_method = true`

Nothing seems to be working. 

I don't have any authorization gems in my app right now (ie, I don't have Pundit, cancan, etc). 

I'm using Rails 5.2, Ruby 2.5.3. Here are my effective versions:
```
    effective_bootstrap (0.6.23)
      bootstrap (>= 4.0.0)
      coffee-rails
      inline_svg
      jquery-rails
      rails (>= 4.0.0)
      sass
    effective_datatables (4.8.1)
      coffee-rails
      effective_bootstrap
      effective_resources
      rails (>= 3.2.0)
      sass
    effective_resources (1.4.10)
      rails (>= 4.0.0)
```

Feeling frustrated that I can't figure this out. Everything seems like such a breeze with this gem!

Any thoughts on what could be going on?

**Comment by matt-riemer** [comment]
Heyo!

I think i know what's going on.

That `actions_col` method calls the `effective_resources` gem, and does a permissions check inside there to figure out what actions are available to your view.

I think the authorize call is actually from within there.

If you haven't yet, try `rails generate effective_resource:install` and see the `config/intializers/effective_resources.rb` file, and make the change to the authorize method in there.

(That `authorize!` comes from the CanCan gem, and is left in there as an example)

Remember to restart your server after making any chances to config intializers.


Thanks for pointing this out, I'm gonna make some changes to remove this dependency, It's literally just 1-line, but it's not right that the permission check is being done in this unexpected spot

Thanks!

**Comment by fanon** [comment]
Hey,
"I'm gonna make some changes to remove this dependency" - Did you ever make the changes? Am facing the same problems like the gentleman in the thread...

**Comment by matt-riemer** [comment]
Hey fanon

Could you try just doing the config.authorization_method in your config/initializer/effective_datatable.rb file and not in the controller?

```
config.authorization_method = Proc.new { |controller, action, resource| authorize!(action, resource) }
```

or

```
config.authorization_method = Proc.new { |controller, action, resource| true }
```
