### ISSUE TITLE
filters work in local development but not in production

### ISSUE THREAD

**Issue by nekapoor** [code-and-effect/effective_datatables#134]
I've got a simple filter setup and this works fine in my local development environment. But it doesn't work in my production environment. I also get this text that appears under the filter. 
Not sure if it's related. I'm not seeing any errors in my console. 

Any thoughts on this? Thanks so much!

<img width="574" alt="Screen Shot 2020-04-30 at 6 34 55 PM" src="https://user-images.githubusercontent.com/1864522/80774255-4ebdfc00-8b11-11ea-9aef-58072a25ad6b.png">

My tech stack: 
Rails 5.2.0
Ruby 2.5.3

hosting on Heroku

**Comment by nekapoor** [comment]
Actually, the `'data-total-records='<number-of-records>' id='some-id'>` line is under all of my effective datatables in production. But they're not in my local dev environment. 

Not sure why that's happening. Let me know if you have any thoughts!

**Comment by matt-riemer** [comment]
Seems like some kind of html escaping issue. I'm not really sure, this is weird :(

**Comment by nekapoor** [comment]
@matt-riemer I figured it out! So for some reason, it's not finding a spinner icon (spinner.svg). So in my rails app, in my assets/images folder, I created an icons folder and a spinner.svg file. Things worked after that!

**Comment by eric5and2** [comment]
@matt-riemer I saw this exact same issue and also had to manually deploy a spinner icon for this to work.

**Comment by matt-riemer** [comment]
Thanks for the info.  I ran into this on one of my newer rails 6 apps instead.

My fix was doing `gem 'sprockets', '< 4'` which seemed to compile the assets (which live in effective_bootstrap) correctly.

I will try to follow up on this with a fix!

**Comment by eric5and2** [comment]
Excellent!  I will try that in my app.  I've been having quite a lot of weird issues with Effective Datatables in Rails 6 that I never experienced before in earlier Rails versions.  Would be very interested in any commentary you can provide on your Rails 6 experiences and things I might need to do differently.

**Comment by matt-riemer** [comment]
I have it running on at least 3 rails6 apps with basically no problems.  Try that sprockets fix, maybe that's all you need.

Sounds like I should update the effective_datatables_demo site to rails6 :)

Appreciate it!

**Comment by matt-riemer** [comment]
Hey,

This has been resolved.  Please upgrade the effective_bootstrap gem (a dependency of effective_datatables) to `effective_bootstrap 0.9.8`

The issue was related to:

https://github.com/rails/sprockets/issues/542

I can see that my assets are correctly being precompiled on a Rails 6 site with Sprockets 4:

https://effective-website-demo.herokuapp.com/
https://github.com/code-and-effect/effective_website

Here's the relevant commit,

https://github.com/code-and-effect/effective_bootstrap/commit/4ad80dc1120a583135628715b3b5b4e1f203e517

Thanks for bringing this up again!
