### ISSUE TITLE
how to make table non-responsive

### ISSUE THREAD

**Issue by rainyhuynh** [code-and-effect/effective_datatables#135]
Dear all,

My table contains many columns, how can I show all the columns on one page and adjust width manual column in there. If I use Table in Jquery I can control all of them.

I try many ways below:

$('#example').DataTable( {
    responsive: {
        details: false
    }
} );

or { "scrollX": true } 

I'm also trying to destroy() and initial them again but not working.

$('#example').DataTable().destroy();
$('#example').removeClass('dtr-inline collapsed');
$('#example').DataTable({responsive: {
        details: false
    }});

Thanks for your help
Rainy

**Comment by matt-riemer** [comment]
Hey great question, in your view:

`render_datatable(CommentsDatatable.new(), input_js: { responsive: false})`

**Comment by rainyhuynh** [comment]
Hi matt,

Yes, great answers. It's working now. Saved my time so much.

Thank you so much.
