### ISSUE TITLE
Show filter in Chart without datatable

### ISSUE THREAD

**Issue by rainyhuynh** [code-and-effect/effective_datatables#137]
Hello,

I want to use a chart (**google chart**) in my project and can filter data in them without Datatable also.

I try to put <%= render_datatable_charts(@datatable) %> in view but can not show filter.

Can you give me advice for this case? This gem is good and I want to use them avoiding add another chart gem here.

Thank you so much.

**Comment by matt-riemer** [comment]
Hey, sorry for the long response time here.

There is a `render_datatable_filters(@datatable)` you could try in addition to the `render_datatable_charts(@datatable)` but I've never really explored this use case of displaying the google charts without the datatable itself.
