### ISSUE TITLE
UUID support

### ISSUE THREAD

**Issue by justDax** [code-and-effect/effective_datatables#140]
Hello, 
I'm trying to implement a datatable on a project and I'm using PostgreSQL.
On my model I have a column named "uuid" that uses Postgre's native UUID type, and I'm getting the following error:

`RuntimeError (unsupported type for uuid)`

The datatable code is very basic:

```
class MyModelDatatable < Effective::Datatable

  datatable do
    col :uuid
    # more columns
  end

  collection do
    MyModel.all
  end
end
```

I altro tried to declare the column `as: :string` but it simply shifts the error from the datatable to the query:

`ActiveRecord::StatementInvalid (PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type uuid: ""`

Is there any additional config that I'm missing?

**Comment by SimoeE86** [comment]
Thanks for your great work Matt!

**Comment by justDax** [comment]
Hey Matt,
I can confirm that upgrading the gem fixes the problem, thank you for your time and support!
