### ISSUE TITLE
Example CRUD inline

### ISSUE THREAD

**Issue by rainyhuynh** [code-and-effect/effective_datatables#143]
Hello,

Can you give me an example for this CRUD inline in this gem?

Thank you.

**Comment by matt-riemer** [comment]
I ran out of time this week but will get an example built and some documentation next week.

I use the inline datatables a lot these days, they're pretty good :)

**Comment by rainyhuynh** [comment]
Hi Matt,
Thank you, I will wait for you.

**Comment by matt-riemer** [comment]
Hey again

I have added a ton of documentation around the Inline feature.

https://github.com/code-and-effect/effective_datatables#inline

Check out a Live Demo
https://effective-datatables-demo.herokuapp.com/things

And the code for it
https://github.com/code-and-effect/effective_datatables_demo

Thanks and have a great day!
