### ISSUE TITLE
Localize the filters and Actions_Col

### ISSUE THREAD

**Issue by Vinnie1991** [code-and-effect/effective_datatables#144]
Hi,
First of all, thanks for this gem!

I want to localize the Filters (for a boolean instead of "Yes/No" I want to use "Ja/Nee") and for the actions_col I want to Show action to be named "Bekijken".

Is this possible?

Thanks!

**Comment by matt-riemer** [comment]
Hey

There's already some basic support for internationalization. Check out

https://github.com/code-and-effect/effective_datatables/tree/master/config/locales

I think if you just add a language locale line one of those to your app, it will work.

Or submit a PR here 👍 

Have a great day
