### ISSUE TITLE
buttons_export_columns not working in input_js

### ISSUE THREAD

**Issue by rainyhuynh** [code-and-effect/effective_datatables#149]
I want to authorize or not user access Print, Copy, Export Excel buttons.

I try `render_datatable(@datatable, input_js: { buttons_export_columns: ':visible:not(.col-actions)' })` but not working.

Can you tell me how to limit that?

Thank you.
Rainy.

**Comment by matt-riemer** [comment]
Hey,

I'm not totally sure what's not working.  I know passing that selector does work

Here's the effective_datatables code wehre I use it

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/initialize.js.coffee#L5

And here are the front end docs for those html5 buttons

https://datatables.net/extensions/buttons/examples/html5/simple.html

**Comment by rainyhuynh** [comment]
Hi Matt,

Thank you for your information, let me try.
