### ISSUE TITLE
any plan on building effective datatables for tailwind?

### ISSUE THREAD

**Issue by nekapoor** [code-and-effect/effective_datatables#150]
Hey! Any chance you're looking to build effective datatables for tailwind?

**Comment by matt-riemer** [comment]
Nah, not really :)

Like, it could probably be done.  The markup for the table itself is very small, and all the related form searches, pagination, etc etc could be rewritten with Tailwind. The existing css is fairly small.

But the official JS "datatables.net" library -- which I do not write or maintain -- https://datatables.net/download/index - Doesn't support TailwindUI.  And this developer hasn't actually used it.

Accepting PRs :)
