### ISSUE TITLE
modal in effective-datatables 

### ISSUE THREAD

**Issue by abasit007** [code-and-effect/effective_datatables#151]
hi there i want have a modal in my effective datatable rows so when i click on rows it shows the modal with my desired info ....anyone knows have any reference how to add modal in effective datatables please mention ...

**Comment by matt-riemer** [comment]
Hey,

There's nothing built in that would popup a modal, but it could be built!

If I was approaching this, I would probably make a datatable column with the content of the modal you want to popup for each row. Keep it hidden. Then a quick javascript event to show the modal.

Maybe something like:

```
datatable do
   col :popup do |post|
       content_tag(:div, modal_html(post), class: 'modal')
   end
```

```
$(document).on 'click', '.effective-datatable tr', (event) ->
  $(event.currentTarget).find('div.modal').modal('show')
```

https://getbootstrap.com/docs/4.0/components/modal/


Good luck!
