### ISSUE TITLE
Stuck on first datatable some doubts.

### ISSUE THREAD

**Issue by lcuevastodoit** [code-and-effect/effective_datatables#157]
Hello, excellent work,
But still I need some help, because I am stuck just in the rendering of the first table of my User model.
This is what it shows me
![image](https://user-images.githubusercontent.com/25910807/120244147-16668100-c22f-11eb-8dde-7c18a67083a8.png)

And a second problem is that I try to see what data the UsersDatatatable model sends from the console and all the variables are empty. So I can't do a troubleshooting
![image](https://user-images.githubusercontent.com/25910807/120244277-6e04ec80-c22f-11eb-8ac3-65a839559780.png)

This is my datatable class

`class UsersDatatable < Effective::Datatable
  collection do
    User.all
  end

  datatable do
    col :id
    col :email
    col :nombres
  end
end`

Thanks in advance!

**Comment by matt-riemer** [comment]
Heyo,

Sorry for the initial headaches :)

I wonder if this has something to do with the `:es` locale.

If you switched back to `:en` would it just work? :/

**Comment by matt-riemer** [comment]
Actually, I know what it is.

Please install the `haml` gem :)

Cheers

**Comment by lcuevastodoit** [comment]
You were right.
I just needed to add 
     gem 'haml-rails' 
Thanks,Now it does show me the table, but when I test the search bar in the datatable it shows me this error in browser
![image](https://user-images.githubusercontent.com/25910807/120245290-5844f680-c232-11eb-81a1-ba4afb018732.png)

In the developer tools I see that the request was made via POST  to
https://my.domain/datatables/users_datatable-606275255219.json
But I dont have a datatables controller

**Comment by matt-riemer** [comment]
You shouldn't need any datatables controller. That's built in.

And that search should totally work. Is it giving you a console error you could post here? :)

**Comment by lcuevastodoit** [comment]
This is the console error
![image](https://user-images.githubusercontent.com/25910807/120245953-727fd400-c234-11eb-8e92-4f1b7027d24f.png)

**Comment by matt-riemer** [comment]
Hmm, I was expecting a 403 error or something. I'm not sure why it would be 404.

The datatables search ajax request isn't even hitting your server?

In my rails server, I would expect to see something like

<img width="1180" alt="bundle_exec_rails_server" src="https://user-images.githubusercontent.com/954468/120246185-bbcc2580-c22c-11eb-830e-4d07c4e1c887.png">

Maybe check out:

https://github.com/code-and-effect/effective_datatables_demo

Sorry this usually just works first time :)

**Comment by lcuevastodoit** [comment]
It is hitting my server
![image](https://user-images.githubusercontent.com/25910807/120246692-a0661800-c236-11eb-897f-5b9189c18df4.png)

**Comment by matt-riemer** [comment]
Hmm, yea perhaps you have some unique config that's preventing these requests.

Here is the routes file:

https://github.com/code-and-effect/effective_datatables/blob/master/config/routes.rb

and the controller it's calling:

https://github.com/code-and-effect/effective_datatables/blob/master/app/controllers/effective/datatables_controller.rb

There's, imho, nothing special going on in either of these that would not respond to json.

Is there something on your app raising a 404, or playing with the request formats? That `ApplicationController.route_not_found` must be your app code, could it be raising a 404 somehow?

**Comment by lcuevastodoit** [comment]
SOLVED: Dude you are an expert
As you said I had this route in the routes.rb, commenting it out eliminated the problem:
`# match '*unmatched', to: 'application#route_not_found', via: :all`

**Comment by lcuevastodoit** [comment]
Thanks.

**Comment by matt-riemer** [comment]
You're welcome! :D
