### ISSUE TITLE
When joining multiple tables (with the Collection) the row count for paging becomes very slow

### ISSUE THREAD

**Issue by rbosch** [code-and-effect/effective_datatables#159]
When I setup my collection 

```
collection do
 Item.joins(:product).left_outer_join(:shelf)
end

```
I see a COUNT(*) query (guess for the paging) that can take easy 2-3 seconds. The loading of the actual data is ~ 0.1 s (on a 1mil. record table).

Anyway to bypass the standard count for the paging (implement my own count per datatable)?

**Comment by matt-riemer** [comment]
Hey, this is an interesting question :)

Unfortunately, I think the answer is: Nope. There's no way to bypass the standard count for paging right now.

Here is the code where we get the size of the collection:

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/datatable_column_tool.rb#L91

You can see it basically just calls `collection.size` which is `collection.count` and executes that SQL query.

Maybe you could do some `.explain` and see why the sql query is taking so long? Maybe adding the correct database index could improve the query performance

**Comment by matt-riemer** [comment]
Maybe change the collection to be something like `Shelf.all.includes(product: :item)` ?

**Comment by rbosch** [comment]
Hi @matt-riemer , thanks for your answer!  I did had a look at the query and indexes, that looks all good. The actual fetch runs under 0.15 seconds. It's just the count that creates issues.

I guess I need to rethink my UI, maybe setup a pre filter. The datatable now shows +18k pages  (50 records/page), thats anyway not useable :o

Maybe an idea for the future: ability to overwrite this count method.
