### ISSUE TITLE
Comparison of Array with Array failed

### ISSUE THREAD

**Issue by tejashande** [code-and-effect/effective_datatables#16]
Hello,

I was trying to perform search & sort on serialized column. The search works appropriate where as the sort gives an error indicating datatables#show **(ArgumentError) "comparison of Array with Array failed**

The column include the blank string. Is there anyway to solve this error?

Thanks in Advance!!!

**Comment by matt-riemer** [comment]
Hey @tejashande !

Any chance you could post a stacktrace and the datatable model file?

I've searched serialized columns with effective_datatables without issues in the past.

There could be something weird going on tho :)

Thanks!

**Comment by tejashande** [comment]
Hey @matt-riemer 

Here is the trace

`ArgumentError (comparison of Array with Array failed):
  effective_datatables (2.3.3) app/models/effective/array_datatable_tool.rb:26:in `sort!'
  effective_datatables (2.3.3) app/models/effective/array_datatable_tool.rb:26:in `order'
  effective_datatables (2.3.3) app/models/effective/effective_datatable/rendering.rb:42:in `table_data'
  effective_datatables (2.3.3) app/models/effective/datatable.rb:72:in `to_json'
  effective_datatables (2.3.3) app/controllers/effective/datatables_controller.rb:20:in `block (2 levels) in show'
  actionpack (4.2.5) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  effective_datatables (2.3.3) app/controllers/effective/datatables_controller.rb:14:in `show'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.5) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  rails-observers (0.1.2) lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
  activesupport (4.2.5) lib/active_support/callbacks.rb:455:in `public_send'
  activesupport (4.2.5) lib/active_support/callbacks.rb:455:in `block in make_lambda'
  activesupport (4.2.5) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.5) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  turnout (2.2.1) lib/rack/turnout.rb:25:in `call'
  i18n-js (2.1.2) lib/i18n-js/middleware.rb:11:in `call'
  warden (1.2.5) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.5) lib/warden/manager.rb:34:in `catch'
  warden (1.2.5) lib/warden/manager.rb:34:in `call'
  client_side_validations (4.2.0) lib/client_side_validations/middleware.rb:15:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run_machine'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.5) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.5) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:9:in `require'
  bin/rails:9:in `<top (required)>'
  spring (1.6.1) lib/spring/client/rails.rb:28:in `load'
  spring (1.6.1) lib/spring/client/rails.rb:28:in `call'
  spring (1.6.1) lib/spring/client/command.rb:7:in `call'
  spring (1.6.1) lib/spring/client.rb:28:in `run'
  spring (1.6.1) bin/spring:51:in `<top (required)>'
  spring (1.6.1) lib/spring/binstub.rb:11:in `load'
  spring (1.6.1) lib/spring/binstub.rb:11:in `<top (required)>'
  bin/spring:13:in `require'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<main>'
`

& datamodel

`
module Effective

  module Datatables

    class Stundents < Effective::Datatable
      datatable do

        default_entries 10

        array_column :first_name
        array_column :middle_name
        array_column :last_name
        array_column :height
        
      end

      def collection
        Student.all.map(&:details).map(&:values)
      end
    end
  end
end
`

Details is an serialized hash column in my case.
It works great for first_name,middle_name & last_name, but it gives an error for height where the key for height is height_(m²)

Thanks for prompt reply!

**Comment by tejashande** [comment]
I found 1 more issue.

Pagination works fine on Array Backed collection where as pagination doesn't work on simple ActiveRecord collection.

The total count of records were > 500 & it says **showing 1 to 1 of 1 entries**

Thanks!

**Comment by matt-riemer** [comment]
Hey again @tejashande,

The ActiveRecord functionality of this gem has had a ton more development time than the Array stuff!

If the key for height is height_m2, I think you should try `array_column :height_m2` instead of `array_column :height`.

As for the total record count, what's the "simple ActiveRecord collection" you're using? (your def collection .. end).  I haven't run into any pagination issues with the ActiveRecord stuff, but I have only really tested on postgres and a bit of MYSQL.  What Database are you using?

Tell me how it works out, thanks! :)

**Comment by tejashande** [comment]
Hey @matt-riemer 

That did the trick for height.. :)

Thanks for your help. But it failed for grade. Key for grade column is **grade_value_(gpa)** & I tried grade_value_gpa. Could you please suggest array column for grade?

I am using MYSQL database.

Thanks in Advance!!!

**Comment by matt-riemer** [comment]
My guess would be `:grade_value_gpa`

You could also try `array_column :grade_value_gpa, name: 'grade_value_(gpa)'

I'm not entirely sure :)
