### ISSUE TITLE
Auto-compute column labels using AR I18N

### ISSUE THREAD

**Issue by banzera** [code-and-effect/effective_datatables#165]
Not sure if I'm just overlooking this feature, but it would be really nice to compute column labels using the Active Record I18N framework (Model.human_attribute_name in particular).

I looked at the code and it looks like the column label is computed either from the passed-in value, or from a simple heuristic using the column name.

I have a patch worked up, let me know if its of any interest.

**Comment by danajanssen** [comment]
Sure :)

**Comment by matt-riemer** [comment]
"one day" we'll build out better internationalization support
