### ISSUE TITLE
bulk actions not behaving properly

### ISSUE THREAD

**Issue by mallikarjunayaddala** [code-and-effect/effective_datatables#17]
bulk actions always calling `show` action of the specified controller.

Example:

`bulk_actions_column do
          bulk_action 'Approve all', bulk_approve_tags_path , data: { confirm: 'Approve all selected posts?' }
 end
`

If I click Approve all, I am getting request to `tags_controller#show` action, not `tags_controller#bulk_approve` action.

Routes file:

`
resources :tags do
    collection do
      post :bulk_approve
    end
end
` 
Am i doing wrong ? 

Kindly let me know.

**Comment by matt-riemer** [comment]
Hey @mallikarjunayaddala 

Thanks for using effective_datatables!! :)

The `bulk_action` is literally an alias for `link_to`.  And I see what's going on....

Your `link_to 'Approve All', bulk_approve_tags_path` is a normal `link_to`, so of course it's a GET action and would route to #show.

You need to add `method: :post` so that rails' UJS will turn the action into a POST and route properly.

**Comment by matt-riemer** [comment]
Yea, looking at the documentation, this is not clear at all.  I think it's wrong in the README for this gem.  I will update it now to include the `method: :post`.

**Comment by mallikarjunayaddala** [comment]
@matt-riemer thanks for your prompt response.
This is very good library, I like it so much!

**Comment by mallikarjunayaddala** [comment]
@matt-riemer 

Hi Good Morning!

This is still not working for me. Can you please help me....

**Comment by matt-riemer** [comment]
Hey again,

Yea, I'm using the bulk actions in one of my rails (4.1.2) apps:

```ruby
module Effective
  module Datatables
    class ManageUsers < Effective::Datatable
      datatable do
        default_order :email

        bulk_actions_column do
          bulk_action 'Enable users', bulk_enable_user_profile_path, data: { confirm: 'Are you sure you want to enable the selected users?' }
          bulk_action 'Disable users', bulk_disable_user_profile_path, data: { confirm: 'Are you sure you want to disable the selected users?' }
        end

        table_column :email

        actions_column
      end

      def collection
        User.ll
      end
    end
  end
end
```

And in my routes:

```ruby
resource :profile, only: [:show, :update] do
    post :bulk_disable_user
    post :bulk_enable_user
  end
```

And my controller:

```ruby
class ProfilesController < ApplicationController
  def bulk_disable_user
    User.where(id: params[:ids]).each do |user|
      user.roles = [:disabled]
      user.save(validate: false)
    end

    render_success_json 'Selected users are now disabled.'
  end

  def bulk_enable_user
    authorize! :manage_users, 'Profile'

    User.where(id: params[:ids]).each do |user|
      user.roles = user.roles - [:disabled]
      user.save(validate: false)
    end

    render_success_json 'Selected users are now enabled.'
  end
end
```

I'm using effective_datatables 2.3.7

I have jquery, and jquery-ujs in my app/assets/javascripts/application.js file.


What's not working with yours?  Do you see the POST being made to your server?  Are there any javascript errors?
