### ISSUE TITLE
weird UI on initial load; refresh fixes it

### ISSUE THREAD

**Issue by nekapoor** [code-and-effect/effective_datatables#171]
Hey! Not sure if this is just a thing for our app, but when I initially load a page with an effective datatable, I get this: 

<img width="1139" alt="Screen Shot 2022-08-06 at 12 04 02 PM" src="https://user-images.githubusercontent.com/1864522/183262769-2f725523-8b50-44af-943a-d3bb19a51470.png">

Page refresh always fixes it. Any thoughts on what this could be? 

Thank you so much!

**Comment by matt-riemer** [comment]
Hey nekapoor!

Those '...' are the default hidden columns. They don't get rendered when hidden.

It looks like your javascript and/or css assets aren't loaded, or this would be displaying correctly.

You mentioned it's fixed after a page load, that's the jQuery.ready working.  Datatables also initializes itself on a turbolinks event. Is there something else going on in your app?

Here's where we initialize it:

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/initialize.js.coffee#L204

Good luck! :)

**Comment by Nerian** [comment]
@matt-riemer Maybe it doesn't work for him because he may be using Turbo instead of turbolinks.

https://turbo.hotwired.dev/handbook/building#observing-navigation-events

Maybe we need to add this for compatibility with the new Hotwire.

```
$(document).on 'turbo:load, -> initializeDataTables()
```

**Comment by Nerian** [comment]
PR at https://github.com/code-and-effect/effective_datatables/pull/172

**Comment by matt-riemer** [comment]
Thanks Nerian!

@nekapoor does this help you? :)
