### ISSUE TITLE
ActionView::Template::Error (undefined method `sql_operation' for #<Effective::Resource:0x00007f91316954a0>

### ISSUE THREAD

**Issue by yo-gen** [code-and-effect/effective_datatables#173]
Current Version of effective_datatables 4.14.2 user effective_resources 1.4.7 which throws above error.
Downgrading to 4.7.16 upgrades effective_resources to 2.2.2 which works as expected.

Is something broken with the current 4.14.2 release or is this expected?

**Comment by matt-riemer** [comment]
Thanks for the heads up!

Yea, upgrading that dependency to latest was the right thing to do.

Cheers!
