### ISSUE TITLE
Out of date jquery.dataTables.js

### ISSUE THREAD

**Issue by flenny** [code-and-effect/effective_datatables#176]
Hey @matt-riemer 👋🏼 
Any chance to get an up to date jquery.dataTables.js in the near future to address some security vulnerabilities?
https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/dataTables/jquery.dataTables.js
Cheers!
Oliver

**Comment by danajanssen** [comment]
Can you link to the release version that has the security fix, please?

Accepting PRs for the upgrade if it can include even some basic manual testing. That will move this along quicker!

**Comment by matt-riemer** [comment]
Hey @flenny 

Your wish has come true!

effective_datatables has been upgraded to the latest datatables.net source code

Enjoy :D

**Comment by flenny** [comment]
Wow that‘s awesome 🎉👌 Thanks a lot!
