### ISSUE TITLE
checkbox invisible in bulk action

### ISSUE THREAD

**Issue by GaneshMaduranathan** [code-and-effect/effective_datatables#18]
@matt-riemer 

Thanks for this beautiful plugin.

I added the bulk action implementation and when I see the table, the checkboxes are not visible.

It looks like the below css (in materialize.css) is making it invisble.

[type="checkbox"]:not(:checked), [type="checkbox"]:checked {
    position: absolute;
    left: -9999px;
    visibility: hidden;
}

When I remove the position and visibility attributes, I can see the checkbox.

Am I missing anything?

Thanks!!!

**Comment by matt-riemer** [comment]
Hey @GaneshMaduranathan 

Glad you're getting use out of the gem! :)

I agree that the CSS you posted would definitely hide the checkboxes.  That CSS doesn't come from this gem tho!

Good luck!! hehe

**Comment by GaneshMaduranathan** [comment]
My bad.

Is there anyway I can do INLINE edit on each row and save? 

Thanks!

**Comment by matt-riemer** [comment]
Hey again,

Nope, this effective_datatables gem doesn't have any kind of inline edit support.

The underlying javascript library does have this feature as a paid option:

https://editor.datatables.net/

Or you could write your own javascript to pop up a modal dialog, edit a row, then update the row and/or call refresh on the underlying datatable.

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/bulk_actions.js.coffee

could be a good place to start

**Comment by GaneshMaduranathan** [comment]
Hello,

I need one more quick help on showing the select options in table header in case of boolean fields.

Say, the column name in the table is "required" with true/false values. The way the column getting rendered in the table is with options "Required,Yes,No", How can I change that to "All,Yes,No" in setting up the datatable properties in the path "app/models/effective/datatables/file_name.rb"

Thanks Again !!!

**Comment by matt-riemer** [comment]
Try

`table_column :is_archived, filter: { values: ['Yes', 'No, 'All'] }`

and then you might need to override the search function as per

https://github.com/code-and-effect/effective_datatables#customize-filter-behaviour

**Comment by GaneshMaduranathan** [comment]
In this case, there will be four options in the select box. "IsArchived","Yes","No","All".. I don't want "IsArchived" instaed I need it to be "All" .that means only three options in the select box. "All","Yes","No".

Overriding search functionality is not a problem !!!

**Comment by GaneshMaduranathan** [comment]
Hello,

Is there any update you have me on this?

**Comment by matt-riemer** [comment]
Are you just trying to change the filter bar collection?

```ruby
table_column :is_global, filter: { collection: ['All', 'Yes', 'No'] }
```

**Comment by GaneshMaduranathan** [comment]
![expected](https://cloud.githubusercontent.com/assets/19199823/15846116/a7b2270a-2c97-11e6-86ce-c9d3b3b8e4c1.png)
![actual](https://cloud.githubusercontent.com/assets/19199823/15846117/a7e029c0-2c97-11e6-80fb-746a76b66066.png)


Please check the screenshots I have attached. I need that "All" label to behave like "Global".

**Comment by matt-riemer** [comment]
This is just calling the simple_form `f.input :global, as: :select` in the background. So any collection you would pass to simple_form will work here.  Maybe what you want is:

```ruby
table_column :is_global, filter: { collection: [['Global', 'All'], ['Yes', 'Yes'], ['No', 'No]] }
```

**Comment by GaneshMaduranathan** [comment]
`<select autocomplete="off" data-column-name="global" data-column-index="4" class="select optional" id="datatable_filter_global"><option value="">Global</option>
<option value="Global">All</option>
<option value="Yes">Yes</option>
<option value="No">No</option></select>`

I want 

`<select autocomplete="off" data-column-name="global" data-column-index="4" class="select optional" id="datatable_filter_global">
<option value="Global">All</option>
<option value="Yes">Yes</option>
<option value="No">No</option></select>`

**Comment by matt-riemer** [comment]
```ruby
table_column :is_global, filter: { collection: [['All', 'Global'], ['Yes', 'Yes'], ['No', 'No']] }
```

**Comment by matt-riemer** [comment]
Hey again @GaneshMaduranathan 

I have your fix here!   Upgrade to effective_datatables 2.4.5

Then use

```ruby
table_column :is_global, filter: { include_blank: false, collection: [['All', 'Global'], ['Yes', 'Yes'], ['No', 'No']] }
```

**Comment by matt-riemer** [comment]
I added the `include_blank` and `placeholder` support, so you can pass both values straight into simple_form

**Comment by mallikarjunayaddala** [comment]
Thanks @matt-riemer!

**Comment by GaneshMaduranathan** [comment]
There you are !!!!! Simply Awesome !!!!

Thanks a ton @matt-riemer :)
