### ISSUE TITLE
Unnecessary POST requests to server....

### ISSUE THREAD

**Issue by mallikarjunayaddala** [code-and-effect/effective_datatables#19]
Hi,

If we'll keep the cursor in the search field in the data table, it is sending requests to server seamlessly on **pressing/holding ALT key** in the keyboard.

How to restrict/avoid this.

Thanks in advance.....

**Comment by matt-riemer** [comment]
Good catch @mallikarjunayaddala!

This has been fixed in effective_datatables 2.6.1

**Comment by mallikarjunayaddala** [comment]
Thank you so much @matt-riemer!
