### ISSUE TITLE
Search is taking too long 

### ISSUE THREAD

**Issue by mallikarjunayaddala** [code-and-effect/effective_datatables#20]
Hi,

**This is fantastic library, I am big fan of this gem. Thanks for wonderful work done by you!**

I am having 50,000 rows in my table, where I am using this gem. Everything is smoothly working, but **Search is taking too long **, some times we are getting **Server Time out error**. How to improve search functionality.

Is there a better way to use search functionality ? or how to improve search functionality.

Kindly help me to overcome this.

Thanks in advance,
Mallikarjuna.

**Comment by matt-riemer** [comment]
Hey @mallikarjunayaddala 

Thanks for enjoying this gem! :)

It's hard to debug a slow query like this....

You have total control over the search functionality by overriding `search_column` and can roll your own search if the built in one is too slow.

I'd suggest using binding.pry in `def search_column` and looking at the collection itself.  You could use http://apidock.com/rails/ActiveRecord/Relation/explain to figure out why the query is slow.

If that doesn't work.  Look at your development log/server console and copy & paste the search query into a program like pgAdmin or psql and do an explain there.

I bet adding a database index to whatever column you're searching on could make a huge speed up!

**Comment by mallikarjunayaddala** [comment]
@matt-riemer
 
Thanks for your  valuable suggestion. I am checking this.

It would be great, **if this gem uses elastic search server for searching functionality.** 

This is possible ? 

Please share your comments.

Thanks in advance,
Mallikarjuna

**Comment by matt-riemer** [comment]
Anything is possible!  I'd love to see an ElasticSearch implementation.  Accepting PRs :)
