### ISSUE TITLE
total_records silently raises and returns 1

### ISSUE THREAD

**Issue by sheldond** [code-and-effect/effective_datatables#21]
Hi there! I am testing your gem out on my project, it looks quite interesting, but I've run into a couple of issues. If you don't mind I'll open them here in Github for your feedback. 

The following line (and 129) is silently raising an error and returning 1: https://github.com/code-and-effect/effective_datatables/blob/71361b8112a7396fcc167b6414d7bd5aa7757a1f/app/models/effective/datatable.rb#L127

I believe the cause may be an incompatible version of mysql2 gem.

For me this code returns an Array, therefore calling `.values` raises an error.
```
>> collection_class.connection.execute("SELECT COUNT(*) FROM (#{collection_sql}) AS datatables_total_count").first
=> [111]
```
```
>> collection_class.connection.execute("SELECT COUNT(*) FROM (#{collection_sql}) AS datatables_total_count").first.values
!! #<NoMethodError: undefined method `values' for [111]:Array>
```

I'm wondering if this can be simplified by just calling `collection.count`?

Thanks for reading this!

**Comment by matt-riemer** [comment]
Hey @sheldond 

Thanks for your interest in this gem.  It is indeed pretty awesome. :)

I have implemented a tiny bit of MySQL compatibility, but 99% of this gem has been developed with postgresql as the backend.

We can't just use `collection.count` here, as sometimes a datatable may have an extremely advanced `def collection` query that will not chain `.count` properly.

This particular line....returns a Hash for me.  Interesting it would return an Array on MySql.

Any chance you have an example app I could check out and reproduce this error?  Or feel upto writing a PR for this that checks the return value?

Thanks :)

**Comment by sheldond** [comment]
Cool thanks for your reply!

I tested this on postgres and indeed it works as expected! 

Since this code is in Rails, not effective_datatables, the behaviour is easy to see by running something like this in any Rails project:

```
User.connection.execute("SELECT COUNT(*) FROM (SELECT * FROM users) AS datatables_total_count")
```

Using `exec_query` will wrap the result in a `ActiveRecord::Result`, which should have a common interface regardless of the db adapter. 

It could be rewritten as (maybe there's something cleaner, but this works):
```
User.connection.exec_query("SELECT COUNT(*) FROM (SELECT * FROM users) AS datatables_total_count").rows[0][0].to_i
```

If the gem does not have full support for mysql I don't think I can use it for my current project, but I will certainly keep it in mind for postgres projects! :D

**Comment by matt-riemer** [comment]
Right on,

I may have time in a few weeks to take a look at this from the mysql perspective better.

Really, all the internals of this gem work with ActiveRecord.  There isn't very much at all custom SQL going on.  So things -should- just work with mysql.  I'm surprised this issues came up, and I know this is working with postgresql, mysql and sqlite projects.

Thanks for the snippet and keep watchin' this repo.

Cheers.
