### ISSUE TITLE
Gem::InstallError: rack requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by sheldond** [code-and-effect/effective_datatables#22]
Hi!

I'm giving this another shot, because after some testing it appears like the only issue with mysql is the one I ran into earlier. :)

I'm trying to bundle this project, but I receive the following error when I run `bundle install`:

```
Gem::InstallError: rack requires Ruby version >= 2.2.2.
An error occurred while installing rack (2.0.1), and Bundler cannot continue.
Make sure that `gem install rack -v '2.0.1'` succeeds before bundling.
```

I'm using ruby 2.1.0, as per the `.ruby-version` file in the repo root.

I believe this issue here might be that the gemspec doesn't specify any gem versions, therefore my bundler is possibly bundling different versions than what you have. I can't easily fix this because I don't know what versions of these gems you are using. :S 

Do you think you could update the gemspec with the correct gem versions? Thanks!

**Comment by matt-riemer** [comment]
Hey again @sheldond ,

Are you trying to bundle the effective_datatables gem itself when you have it checked out locally?  This isn't useful.  There's nothing to bundle.  There's no tests to run :)

You just want to add it to an existing rails app.

The only gems we define are:


  s.add_dependency "rails", [">= 3.2.0"]
  s.add_dependency "coffee-rails"
  s.add_dependency 'kaminari'
  s.add_dependency "sass-rails"
  s.add_dependency "haml-rails"
s.add_dependency "simple_form"

And the .ruby-version shouldn't matter! Infact, I'ma remove those!

**Comment by sheldond** [comment]
Hi Matt, ah I see! After reading the readme I understood there were some tests, but now that I look I see there are none, oops!

I was able successfully bundle install using ruby 2.3.1!

Thanks for your help!
