### ISSUE TITLE
State saving

### ISSUE THREAD

**Issue by dhallek** [code-and-effect/effective_datatables#25]
First of all, thank you for this very useful gem.

Is there a way to save the state (filtering, pagination, sort order, ...) of the datatable between multiple requests?

**Comment by matt-riemer** [comment]
Hey @dhallek 

...Nope!  There's no support for the save state right now.

There is support for it in the datatables.js library

https://datatables.net/examples/basic_init/state_save.html

But I haven't looked into working that into this gem.

Everything in effective_datatables is server/ajax driven, so it's probably not as easy as just adding a config option to the javascript.  Sorry :(

**Comment by dhallek** [comment]
Thanks for the quick response Matt! I'll try to figure something out for my project. If the result is worth sharing I'll let you know.
