### ISSUE TITLE
Using a custom filter input.

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#26]
Hi,

Awesome gem, thank for it.

I have a question regarding the filter. I have this code:

```ruby
array_column :member, filter: { :as => :select, :collection => current_space.members } do |invoice|
  link_to invoice.member.name, manager_accounting.member_path(current_space, invoice.member)
end
```

As you see, it uses a `select`. But this list of members could be really big, so I would really like to use a `:chosen` field – an autocomplete similar to select2. Normally I can create a chosen field with as: :chosen; I am using simple_forms.

I tried replacing the `as: :select`  with `as: :chosen` , but it just doesn't output anything on the header. No error message, just an head row with just a label and no input field.

How can I do this?

I see the code that handles this is defined at https://github.com/code-and-effect/effective_datatables/blob/master/app/helpers/effective_datatables_private_helper.rb#L82

Maybe I could make a push request that adds a new input type. But maybe in the long term we should extract this so that it is more easily extended. I am thinking of something similar to how SimpleForm allows you to extend the custom input fields.

**Comment by matt-riemer** [comment]
This is already done if you install effective_form_inputs gem as well (it uses select2 tho, not chosen).

Will consider this for the 3.0 branch, make it easier to just pass an entire attributes to simple_form.
