### ISSUE TITLE
Reset scope function not working

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#29]
Hi,

So when I create a scope and display it on the view, there is a 'Reset button'. But is not working.

Perhaps its implementation was not finished?

When you click on it, it triggers a reset event on the form, but there no handler for that event defined anywhere, so nothing happens:

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/scopes.js.coffee#L3

**Comment by matt-riemer** [comment]
It was just intended as a form reset!
