### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#31]
Hi,

Currently the scopes functionality requires a full reload of the page. Wouldn't it be better to avoid a full reload and simply make Datatables reload the page via Ajax?  What was the rationale behind that decision? Will you accept a pull request to implement that?

**Comment by matt-riemer** [comment]
Hey @Nerian 

Amg man you're a beast. chewing through this gem :)   I will respond to your other Issues later today.

I am actually working on a 3.0 branch of effective_datatables...where this has already been implemented.  Kind of.

There's a catch or two with it...(datatables js doesn't support dynamic columns).

Thanks for everything!

**Comment by Nerian** [comment]
Cool, that sounds great. In my case I don't require dynamic columns.

Thanks :)

**Comment by matt-riemer** [comment]
Hey @Nerian, 

Thanks so much for your pull requests.  I get a small number of Issues opened, but very few outside contributors send PRs.  Thanks for working through these issues!

I have merged all your changes to-date, and released effective_datatables 2.12.0

I use this on a ton of my client-facing websites, and it gets a lot of development time / love.

I hope the gem is working out well for you, with these adjustments :)

**Comment by Nerian** [comment]
It's a fantastic gem, you have done a great job at documentation and the DSL is really nice. It doesn't seem to be a popular gem ( I found this project in https://www.ruby-toolbox.com/) , but it really is the best because it packages everything you need for interactives tables so I think it has a great potential. I am looking forward to use the effective_form_inputs too.

Those new features sounds really good. One thing I could use too is the ability to render a partial for the scopes, instead of the automatic view. The default view is great for prototyping, but I can see things that I would to different for some complex UI I have in mind for my project. The ability to use partials for the scopes, as you can use for the actions, would be really nice. But I am unsure how would that play out with the changes you plan to do in order to support Ajax powered scopes.

Let me know if you need some help or want to testing done, I plan to use this gem extensively so I will help you :)

Thanks!

**Comment by matt-riemer** [comment]
The documentation has kind of fallen behind implementation....You can pass an `partial:` to the scopes declaration...Or you could override /views/effective/datatables/_scopes.html.haml entirely.

It's probably not as full featured as it could be! :)

I'll totally shoot you a message as I get the 3.0 going, I'd love some help testing.  Thanks @Nerian !!

**Comment by Nerian** [comment]
Excellent. Thanks.
