### ISSUE TITLE
CMD + A  doesn't work when on a filter input. 

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#35]
Hi,

In Mac OS you can click `_CMD_ + A` to select all text on an input field. But when I do this on one of the text fields for filtering, nothing happens –  the CMD keypress is ignored, and a 'A' character is added to the input. 

CMD+A  is useful when you want to clear the filter in a quick way, so I think the user should not be prevented form doing this.

I suspect EffectiveDatatables is capturing the relevant key events somehow.

**Comment by matt-riemer** [comment]
good catch.  Probably something to do with the javascript events, yea.  There's a lot going on there.

This should be looked at
