### ISSUE TITLE
Bug: grouped_select doesn't support procs.

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#36]
Hi,

I have this code:

```
table_column :holder, filter: { as: :grouped_select, collection: Proc.new { holder_collection } } do 
  ...
end

def holder_collection
  {
    'Members' => current_space.members.joins(:payments).map { |p| [ p.name, p.to_global_id.to_s ] },
    'Suppliers' => current_space.suppliers.joins(:payments).map { |p| [ p.name, p.to_global_id.to_s ] }
  }
end
```

But this fails with:

```
Grouped collection expecting a Hash {'Posts' => Post.all, 'Events' => Event.all} or a Hash {'Posts' => [['Post A', 1], ['Post B', 2]], 'Events' => [['Event A', 1], ['Event B', 2]]}
```

Notice that's using a :grouped_select. A :select works fine. In other words, :select can handle Procs, but :grouped_select can't. 

I believe it should be supported, right?

One more question, do we really need to use a proc if we are going to have dynamic content (results of a query) or can we just use User.all (for example) without a Proc?

I suspect we need to use a Proc because this class is evaluated just once on code load, so we use a Proc to get up to date data on each request, but I wanted to confirm my understanding.

**Comment by matt-riemer** [comment]
oooh good catch. I'll take another look at this!

**Comment by matt-riemer** [comment]
I think this is a moot point in datatables 3.0.  It's jsut around the corner.
