### ISSUE TITLE
Bug: Exceptions from a Proc for a collection parameter does not bubble

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#37]
Hi,

This code does not fail:

```
table_column :something, filter: { :as => :select, :collection => Proc.new { raise StandardError.new('hi!') } }
```

It just gives you a table without the select filter for that particular column. No error.

This makes errors a little bit difficult to find and fix. It's probably some of the `rescue` clauses on the code. I noticed that most of them are set to rescue all exceptions. Perhaps that could be changed to just rescue StandardErrors – or relevant exceptions for that code section.

**Comment by matt-riemer** [comment]
3.0 is going to drop support for procs in the collection, as they're no longer needed!
