### ISSUE TITLE
Length of table

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#41]
Hi,

I am trying to have one of the tables default to have 5 rows. I tried to `lengthMenu` but it doesn't seem to have an effect.

```
= render_datatable(@invoices_table, { "lengthMenu" => [ 5, 25, 50, 75, 100 ] })
```

Thoughts?

**Comment by matt-riemer** [comment]
I think that code should work!  At least to initialize the javascript with that lengthMenu.

Try another syntax, the original lengthMenu is:

```
lengthMenu: [[10, 25, 50, 100, 250, 1000, -1], ['10', '25', '50', '100', '250', '1000', 'All']]
```

**Comment by matt-riemer** [comment]
I bet this is it...

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/effective_datatable/ajax.rb#L52

**Comment by matt-riemer** [comment]
If you wanna make a PR to add 5 to that, I can merge it straight away

Been way too busy this March to do much open source work.  I'm gonna have that three-point-zero branch done soon tho :)

**Comment by Nerian** [comment]
Using this syntax I get the list to show 5, and 5 to be the selected option, but the table displays 10 initially anyway. Manually changing from the select does get it changed.

```
= render_datatable(@invoices_table, pageLength: 5, lengthMenu: [[5, 10, 25, 50, 100, 250, 1000, -1], ['5', '10', '25', '50', '100', '250', '1000', 'All']])
```

I made the PR:
https://github.com/code-and-effect/effective_datatables/pull/42/files

I am thinking that this would be a good candidate for a configurable parameter in the initializer instead of hardcoded.

Thanks for your work :)
