### ISSUE TITLE
Changing DOM value for all tables

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#43]
Hi,

I would like to have change the DOM value for all tables. Specifically I want to have the length selector and export buttons at the bottom instead of on the top. I am currently doing this:

```
= render_datatable(@invoices_table, dom: "<'row'<'col-sm-12'tr>><'row'<'col-sm-6'i><'col-sm-6'p>><'row'<'col-sm-4'l><'col-sm-8'B>>")
```

But I have many tables, and so it would be better to centralise this value. I think having a config option on the initializer would be good.

**Comment by matt-riemer** [comment]
yea, config initializer is reasonable idea.  I would accept a PR for it :)

**Comment by Nerian** [comment]
Closing because you got it implemented? I can work on it if it is not; I just haven't got to it yet.

**Comment by matt-riemer** [comment]
aaw I just kind of closed this due to inactivity. :)

You should check out the three-dot-zero branch. It's working great for me in a pretty complex app but it needs another set of eyes.

Cheers

**Comment by Nerian** [comment]
Cool :)

I notice the 3.* branch is missing 6 commits from master. I gave it a try bringing it up to date, but there are some conflicts I am not sure how you want to solve. If you merge I can test the branch against my code and I will report any bugs I discover.
