### ISSUE TITLE
Ajax requests broken after "Clean up classify"

### ISSUE THREAD

**Issue by dhallek** [code-and-effect/effective_datatables#44]
After updating the effective_datatables gem from version "2.6.11" to "2.12.0" the ajax requests for the datatables in our app are broken.

For a simple datatable such as:
```
# app/models/effective/datatables/users.rb

module Effective
  module Datatables
    class Users < Effective::Datatable
      datatable do
        table_column :email
        table_column :last_name
        table_column :first_name
        ...
        actions_column
      end

      def collection
        User.all
      end
    end
  end
end
```

... the ajax request used to call something like:
`localhost:3000/datatables/users.json`

... but it now calls:
`localhost:3000/datatables/effective%2Fdatatables%2Fusers.json`

This does not work well with our webserver setup (Apache + Passenger) as the forward slashes (%2F) in the URL result in Apache returning a 404 page.

After a quick look at the commit history the issue is probably related to [commit b55291a: Clean up classify](https://github.com/code-and-effect/effective_datatables/commit/b55291ac0e889708d86063a2101ac4234809c77c).

Suggested solution: avoid using forward slashes in the ajax URLs.

**Comment by matt-riemer** [comment]
Hey @dhallek !

Thanks for reporting this bug!  Most of my rails apps run on heroku with a mix of puma, unicorn and phusion passenger.  I hadn't run into this bug.

I'll have a chance to take a look at this in the next few days.  For now I'd stick with the older version...you won't find too much value upgrading from 2.6 to 2.12.   FYI there's a 3.0 coming out soon that's a huge revamp.  I'll keep this ajax url in mind for it.

Thanks again, especially for tracking down the commit. Makes things easier.

**Comment by dhallek** [comment]
Thanks for the quick response @matt-riemer ! For now we will indeed stick to the older version. Looking forward to the revamp!
