### ISSUE TITLE
Datatable break when we use it with turbolink

### ISSUE THREAD

**Issue by uzaif313** [code-and-effect/effective_datatables#45]
Hi,
Thanks for a great Gem
i am using rails 5 with turbolink ,
effective datatables is working fine initial page load but whenever page transition occur its lost datatables beauty. is there any work around

**Comment by matt-riemer** [comment]
It should work just fine with turbolinks!  Are there any javascript console errors?

Try the 3.0 branch (which is just aboot to be released):

gem 'effective_datatables', github: 'code-and-effect/effective_datatables', branch: 'three-dot-zero'

https://github.com/code-and-effect/effective_datatables/tree/three-dot-zero

**Comment by uzaif313** [comment]
I am using latest version of  `effective_datatables` gem
no there is no `js` issue in console its seems that when my page transit data table is not showing searching and sorting feature 

another question
How can i create single text input for search which will allow me to search whole column?

**Comment by matt-riemer** [comment]
Yea, I'm not sure what would be up with those javascript issues.

My javascript asset pipeline looks something like:

```
//= require jquery
//= require jquery_ujs
//= require turbolinks

//= require bootstrap-sprockets

//= require effective_datatables
//= require effective_form_inputs
```

To add a search field for string, just use

`table_column :name, filter: { as: :string }` (2.x)
`col :name, search: { as: :string}` (3.0 branch)
