### ISSUE TITLE
version 3 error when rendering

### ISSUE THREAD

**Issue by billspat** [code-and-effect/effective_datatables#46]
Thanks for this gem, it looks really great.  Have a problem with 3.0 branch where master branch works ok.  Using Rails 4.2.8 and ActiveRecord.   Error when rendering view: 

```
.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/effective_datatables-13f24c24b6b2/app/views/effective/datatables/_datatable.html.haml where line #10 raised:

no implicit conversion of nil into String
```

Perhaps I don't understand the new DSL.   User has authorization, and I've even tried turning setting authorization to false. 

Here is the model:

      class SpeciesDatatable < Effective::Datatable 
        collection do 
          Species.all
        end

        datatable do
         col :id
         col :genus
         col :species
        end

      end

This is a subset of the columns in the table.  Using MySQL (in development) and table has no indexes other that primary key on ID.  

View and Controller are as described in readme.   Using the generated initializer Same error for `render_simple_datatable(@datatable)` or `render_datatable(@datatable)` 

I've tried adding 

    datatable do
       order :id, :desc
    ....

but get the same error.  

Hopefully this is helpful, sorry I'm reporting a problem with no suggested fix.  Happy to provide more info.  Best of luck on v3

**Comment by SimoeE86** [comment]
Same problem and similar configuration (Rails 4.2.8, myslq2 0.4.6).
The problem seems to be on the row 28
../effective_datatables-3.0.7/app/helpers/effective_datatables_helper.rb -> 'display-records' => datatable.to_json[:recordsFiltered]
@billspat How did you solve it?
Thank you

**Comment by matt-riemer** [comment]
It's possible there's a rails 4.2 issue at play here.

I've been doing most of the development in Rails 4.1 and Rails 5.0

Thanks for the bug report @SimoeE86, i'll look into this.

**Comment by matt-riemer** [comment]
Hey again,

I upgraded one of my Rails 4.1 apps to Rails 4.2.8 to give this a try.  I ran into no problems!  Definitely not an exception like you seem to be encountering

I have a datatable something like this:

```ruby
class ThingsDatatable < Effective::Datatable
  datatable do
    order :letter, :asc

    col :name
    col :letter
    col :position

    actions_col
  end

  collection do
    Thing.all
  end
end
```

**Comment by SimoeE86** [comment]
Hi, thanks for the support.
I created a clean new project using:
- rails 5.1.1
- ruby 2.4.1
- mysql2 0.4.6
- effective_datatables 3.0.8
Same problem.
I attach the project if you want check.
Thanks for your assistance

[test_datatables.zip](https://github.com/code-and-effect/effective_datatables/files/1044597/test_datatables.zip)

**Comment by matt-riemer** [comment]
I don't want to install MySQL lol :(

**Comment by matt-riemer** [comment]
Hey @SimoeE86 

Maybe this is too little too late.  But this bug has been fixed.

Please upgrade `effective_resources` gem (a dependency of effective_datatables) to 0.3.10  

It has the appropriate MySql fixes.

Cheers!
