### ISSUE TITLE
Column Width

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#48]
Hi,

In the previous version I could set a custom width like this:
```
table_column :paid, label: 'Status', width: '70px'
```

But this doesn't work anymore. I get a wrong key error. How do I do this now?

**Comment by danajanssen** [comment]
Not sure if there is still a width option, but you should probably be defining width via CSS. Your column will have an automatically generated class assigned (e.g. .col-paid) that you can target. This is also good for applying things like whitespace: nowrap on columns that you don't want to wrap.

**Comment by Nerian** [comment]
That's a good idea, thanks.

I just did this:

```
.col-actions{
  width: 100px
}
```

**Comment by matt-riemer** [comment]
Yep, width keyword was removed.  use css!
