### ISSUE TITLE
Accessing the cookie or attributes

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#49]
Hi,

I am using a partial to display one of the columns. I need to have access to the attributes that were passed to the EffectiveDatatable, but I am not sure how to do it.

Example:

```
@members_table = OrganisationMembersDatatable.new(self, organisation_id: current_organisation.id)
```

In the partial I need to have access to that `organisation_id`. This works fine when the table is first rendered, since the organisation_id parameter is available as part of the `params` hash. But when performing a search on the column the params are empty, because – as I understand it – Effective Datatables now uses a cookie to store that info.

How do I get access to that cookie?

I tried this:

In the `Effective::DatatablesController` I put a binding.pry to take a look at the params:

```
[2] pry(#<Effective::DatatablesController>)> params
=> <ActionController::Parameters {"draw"=>"3", "columns"=>{"0"=>{"data"=>"0", "name"=>"name", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"sad", "regex"=>"false"}, "visible"=>"true"}, "1"=>{"data"=>"1", "name"=>"tags", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}, "2"=>{"data"=>"2", "name"=>"_actions", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"asc"}}, "start"=>"0", "length"=>"25", "search"=>{"value"=>"", "regex"=>"false"}, "cookie"=>"074072723805", "locale"=>"en", "controller"=>"effective/datatables", "action"=>"show", "id"=>"organisation_members_datatable", "format"=>"json"} permitted: false>
``` 

I noticed that there is a `"cookie"=>"074072723805"` parameter, but when I did `cookies['074072723805']` it's nil.

So, in a view, how do I get access to the attributes that were passed to the EffectiveDatatable?

**Comment by Nerian** [comment]
Oh and you used to be able to just call `attributes` in the view. But that's gone too.

**Comment by Nerian** [comment]
I solved it by creating a helper:

```
def datatable_attributes
    if @datatable
      @datatable.attributes
    else
      {}
    end
  end
```

That works. But having an `attributes` helper by default as it used to be would be better :)

**Comment by matt-riemer** [comment]
I think you figured this out!! The `@datatable.attributes` is what I intended to be called :)

I can improve documentation on this. Thanks @Nerian !!
