### ISSUE TITLE
Custom search

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#50]
Hi,

I am trying to implement a custom search method, but the collection I am getting in the search method is an array instead of a scope.

```ruby
col :member_id, sort: false, label: 'Member', search: { as: :select, collection: members_collection } do |charge|
  link_to charge.member.name, manager_accounting.member_path(current_space, charge.member)
end.search do |collection, term, column, sql_column|
  collection.joins(:invoice).where(invoices: { member_id: term })
end

collection do
  charges = current_space.charges.includes(:payment_method, :invoice, invoice: :member)
end
```

The `collection` in the `search` method holds an array of arrays. But what should be coming out of the collection block is a scope.

This is the type of the `charges` variable in the collection block:
```
[2] pry(#<Effective::DatatableDslTool>)> charges.class
=> Charge::ActiveRecord_AssociationRelation
```

What am I doing wrong?

**Comment by matt-riemer** [comment]
I would expect the `collection` there to be an `ActiveRecord::Relation` there.  Can I see the whole datatable?  Could be something weird going on.

**Comment by Nerian** [comment]
Sure: https://gist.github.com/Nerian/8dfd73cfc37fa5007b34403fde084729

**Comment by Nerian** [comment]
Here: https://gist.github.com/Nerian/d1391d2773acfbffb3b0b131fc986e41

**Comment by matt-riemer** [comment]
I think datatables is treating `member_id` as an array-based column, because `Charge.new` doesn't respond to `member_id`.

Try adding `sql_column` to the `col` line:

```ruby
col :member_id, sql_column: 'invoices.member_id'
```

**Comment by Nerian** [comment]
Nice :)

That fixes it. Should we consider this a bug or should I be adding this parameter in other places too?

**Comment by matt-riemer** [comment]
I don't consider this a bug.

Datatables is pretty smart about a single model (with it's belongs_to and has_many) but when you're doing crazy joins and such it needs a little bit of help :)

I will add to the documentation about this!

Thanks as always @Nerian
