### ISSUE TITLE
Some interesting edge case

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#51]
Hi,

I have another interesting sample:

```ruby
col :status, sql_column: 'something', sort: false, search: { as: :select, collection: [['collected', :collected], ['pending', :pending], ['failed', :failed]] }  do |charge|
    charge.status.humanize
end.search do |collection, term, column, sql_column|
  case term
  when 'collected'
    collection.collected
  when 'pending'
    collection.pending
  when 'failed'
    collection.failed
  end
end
```

The `:status` column is not backed by a database column. It's an artificial value calculated on the model. There are also scopes for each of the possible values. 

Normally I would get an array here instead of a collection. But on the search I wanted to be able to use an actual active record relation and not an array. I was getting an array, because the `charge` doesn't have a column named `status` (it does have that method though). I got it to give me a relation by adding a `sql_column` parameter – but notice that the value is 'something', it's not used at all. 

I was wondering if this is the best way to do this or you could point to me on a better path. I could be using a filter, but I really think it is better to put this in the column.

**Comment by matt-riemer** [comment]
Yea, If I was writing this, I'd probably use the filter bar for this....

But, I like this problem!  I think this can still be done.

Option 1
==========
It breaks the rules a bit, but you could consider the current search in your collection block.

Play with something like this:

```
collection do
  scope = Charge.all

  # Check out attributes, search, filters, and state here
  if search[:status] == 'collected'
    scope = scope.collected
  end
  scope
end
```

And then you might still need to override the `col.search` to just return the collection -- don't do anything -- and cancel out the search at that point.

This might break the pagination and filtered / total records.

Option 2
===========

Try overriding `def scope`

class ChargesDatatable < Effective::Datatable
  datatable do
    col :name
  end

  collection do
    Charge.all
  end

  def scope
     # Check out search, filters and state here too
     if search[:status] == 'collected'
        :collected
     end
  end

end

**Comment by Nerian** [comment]
Thanks for tips!

Another interesting thing:

I have got this column:
```
col :member, search: { as: :select, collection: Member.all } do |contract|
      link_to contract.member.name, manager_accounting.member_path(current_space, contract.member)
    end
```

And this gives me this UI:

<img width="283" alt="captura de pantalla 2017-06-16 a las 12 17 42" src="https://user-images.githubusercontent.com/259568/27222793-ff47324a-528d-11e7-85a9-f1fc60b6a11b.png">

I could fix this by `.map { |i| [i.name, i.id] }`. But if I change it to this instead:

```
    col :member, search: { as: :select, collection: Proc.new { Member.all } } do |contract|
      link_to contract.member.name, manager_accounting.member_path(current_space, contract.member)
    end
```

I get this:

<img width="323" alt="captura de pantalla 2017-06-16 a las 12 17 26" src="https://user-images.githubusercontent.com/259568/27222814-108ea920-528e-11e7-909d-8dc904d3ba64.png">

So looks like Proc is still needed?

**Comment by matt-riemer** [comment]
I think this is doing the right thing now

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/effective_datatable/resource.rb#L94

Try the unlucky effective_datatables 3.0.13
