### ISSUE TITLE
The actions_col are not present in the Show/Hide interface.

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#55]
Hi,

I noticed that the `actions_col` are not present in the Show/Hide interface, but they do get collapsed, so there is not way to uncollapse them unless you click on the 'Show All button'.

I would suggest:

1. Collapse action columns the last.
2. Add the controls to the list of collapsable columns in the UI. Not a high priority for me, though – my issue actions collapsing.

Also, is there a way to disable the responsive behavior globally, or per effective datatable?

I tried adding `responsive: 1` but the column still gets to be hidden,

**Comment by matt-riemer** [comment]
We do pass a responsive of 5000 to the actions column.

They're always last / don't collapse on my firefox! hmm

**Comment by Nerian** [comment]
Mmm, weird. I will try to replicate another time. I am using Chrome. It may be a problem with Selenium.
