### ISSUE TITLE
Filters outside of Datatable.

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#56]
Hi,

I have got some complex filters in mind and I would like to create a partial and put a simple_form form there and use it as the filters of a datatable.

In other words, I would like a custom filter toolbar.

Is it possible?

**Comment by matt-riemer** [comment]
Yep, I think this is actually pretty easy.

Just override `views/effective/datatables/_filters.html.haml` in your own app.

If you stick to the same `scope` as a single value, and `filters` can be anything data model, everything might just work....

:)

All the filter logic is in `app/models/effective/effective_datatable/state.rb` fyi

**Comment by matt-riemer** [comment]
There's also `app/helpers/effective_datatables_helper.rb` and the `render_datatable_filters` helper method you could override if you want more control over what partial is rendered

**Comment by Nerian** [comment]
Thanks :)

But that will change the of all filters. My intention is just to change one table. Basically, instead of using the filters DSL, I would like to hand code my own form.
