### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#59]
Hi,

Since this https://github.com/code-and-effect/effective_datatables/commit/0230a4c16a0f12939b3aa7e093dd37855fb99cf1 change, I noticed that the arrow is not correctly positioned – see per page number.

<img width="564" alt="captura de pantalla 2017-10-16 a las 11 54 04" src="https://user-images.githubusercontent.com/259568/31606204-c2f43122-b268-11e7-8316-cd4e7c6ec105.png">

Removing max-width: 45px; fixes it for me.

Also, this line: https://github.com/code-and-effect/effective_datatables/blob/0230a4c16a0f12939b3aa7e093dd37855fb99cf1/app/assets/stylesheets/effective_datatables/_overrides.scss#L83

Adding a little bit of padding to the right make it better so as to make "Showing 1 to 1 of 1 entries" does not merge with the with "10 per page" part.

**Comment by matt-riemer** [comment]
Thanks for the feedback!! 

Yikes, that line displays pretty badly on yours.  It lines up perfectly on mine of course :)

I knew we'd run into a few css issues with this new update, and will try to get them fixed before pushing another gem version.

Thanks :)

**Comment by matt-riemer** [comment]
I think this might be an app specific issue (of your! bwuahaha)

I'm running this in a few different bootstrap3 apps now and am not having the same display.

I should really really really get a demo app built with just plain bootstrap3 and a datatable to make sure.

I'm gonna close this for now tho.

Thanks as always Nerian :)

**Comment by Nerian** [comment]
Oh my, sorry to waste your time :)

After much searching I found the problem.

I am using select2 with the bootstrap theme, and not the one packaged with effective-forms.
https://github.com/select2/select2-bootstrap-theme . So the styling is different and that explains the wrong UI.

I am not using effective-forms because I was already using a different datepicker and select. Maybe in the future I may upgrade.

**Comment by matt-riemer** [comment]
Aah yea that makes sense.  Thanks for linking me to that select2-bootstrap-theme...I'll check it out.

I'm waiting for bootstrap4 to be ready and that's gonna be a massive upgrade of all the effective gems. yikes!
