### ISSUE TITLE
actions_col doesn't work with nested resources

### ISSUE THREAD

**Issue by holgum** [code-and-effect/effective_datatables#61]
I have a nested resource:
```
  resources :accounts do
     resources :transactions
  end
```
I created a datatable model for transactions, but couldn't figure out why the actions where not rendering any icons until I realized it must be the fact that the paths are nested.  I worked around it by doing something like this:

```
    actions_col do |tx|
       link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_account_transaction_path(tx.account_id, tx)
    end
```

which works fine, but I wondered if there is some way to tell effective_datatables (or effective_resources?) that this is a nested resource so that it 'just works'.
If not, might be nice to have a mention in the docs.

**Comment by matt-riemer** [comment]
Hey @holgum 

Great question :)

Nope!  Currently, there is no automatic support for nested resource actions.

Totally a feature I'd like to make happen, but doesn't exist right now. (I've run into this on my own projects as well, and it's on my mental TODO list.)   Accepting PRs :)

Your workaround is the right idea, and you could also use:

```ruby
edit_icon_to(edit_account_transaction_path(tx.account_id, tx))
```

or

```ruby
glyphicon_to('pencil', edit_account_transaction_path(tx.account_id, tx))
```

from the effective_resources gem.

https://github.com/code-and-effect/effective_resources/blob/master/app/helpers/effective_resources_helper.rb#L72

to slightly tighten up those actions.

Cheers :)

**Comment by holgum** [comment]
Thanks for the prompt reply. 
Knee deep in another project right now and probably not the right one to tackle a PR for this kind of thing anyway, but if I get freed up later I may have a look. 
In the meantime keep up the good work. I like this concept. Would like a bit more control over display aspects of the table if possible (row heights, col widths, stuff like that).

**Comment by danajanssen** [comment]
I use the automatically generated class names to style columns e.g. if I have a column named 'user' it will have a class of '.col-user' that I can target for things like no-wrap and width. This class can be customized with the "col_class" option on your col. You should also be able to target height via CSS but that's not something I modify with, usually. Hope some of this helps!

**Comment by matt-riemer** [comment]
Hey @holgum 

Give the new 3.3.7 version of effective_datatables a shot.

The `actions_col` link behaviour should be generating the right nested resources aware edit url now.  

Of course, you still need authorization on both objects for the link to be displayed.

Rails routes stuff can be really tricky!

Thanks

**Comment by holgum** [comment]
Finally got around to updating this (with 3.3.8) and indeed my nested routes actions_col work now.  Very nice!  
Now I have another (possibly stupid) question: the destroy icons pop up confirmation messages with object ids (e.g. "Delete #<Transaction:0x00007fe4e002aef0>?" ), so I'm back to custom coding the destroy links to get something more user friendly.  Or am I missing something?

**Comment by matt-riemer** [comment]
sure, great question!

Just add a `to_s` method to your Transaction, and effective_datatables will use that instead of "#Transactionx0000"

**Comment by holgum** [comment]
That was easy! Thanks again. Love this gem!
