### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#62]
Hi,

So I have got an application that has the following authorisation roles:

* Admin
* Owner
* Member
* Manager

And my application has to serve multiple clients. So each user has a role that is scoped to a particular client. Classic multi-tenant app.

I have this initialiser:

```ruby
config.authorization_method = Proc.new { |controller, action, resource| datatable_authorization_method(controller, action, resource) }
```

And this on my application controller:

```ruby
  def datatable_authorization_method(controller, action, resource)
    datatable = controller.instance_variable_get(:@datatable)

    return true if datatable.blank? # We are in one of our own controllers; so permissions are handled in BaseController.
    return true if datatable.attributes[:require_role].blank?

    # We are in Effective::DatatablesController
    case datatable.attributes[:require_role]
    when :owner
      return current_user.account_owner?(current_account)
    when :admin
      return current_user.account_admin?(current_account)
    when :manager
      return current_user.account_manager?(current_account)
    when :member
      return current_user.account_member?(current_account)
    else
      raise NotImplementedError.new
    end
```
And I instantiate an effective datatable like this:

```ruby
def index
    @contracts_table = ContractsDatatable.new(self, account_id: current_account.id, require_role: :manager)
end
```

And it works fine, so far. But I think it is a little bit hacky to have that `datatable = controller.instance_variable_get(:@datatable)`. I was wondering if the `@datatable` could be one of the arguments that are passed to the `authorization_method`. So that it would be like this:

```ruby
config.authorization_method = Proc.new { |controller, action, resource, datatable| datatable_authorization_method(controller, action, resource, datatable) }
```

That way I can be confident that it will not break. What do you think? Or if you could suggest a different alternative.

**Comment by matt-riemer** [comment]
Hmm! You and I definitely do authorization differently.

In my mind, the `EffectiveDatatables.authorized?(controller, action, resource)` is just flow-through to the controller's  (I use CanCanCan) check. So my methods are always 

```ruby
config.authorization_method = Proc.new { |controller, action, resource| authorize! :action, resource }
```

But you're using it more to see if you can view the table at all.

**Comment by Nerian** [comment]
But how do you check that a user has access to a particular resource? Not to a particular category of resources, but to a particular resource?

Say you have multiple Room and multiple students. Some students should have access to a room and not to others. How do you check that?

You will have no problem when the datatable is first rendered, because you are probably already handling permissions before. If the user does not have access to the Room page, it will not get to see the datatable anyways. 

But when you use the filters, the controller that gets the request is Effective::DatatablesController. So your controller's checks are bypassed and only the `authorization_method` is used. 

In that case, the three arguments are the controller (Effective::DatatablesController), action (:index), and resource – which is just a class name and not the actual resource.

So how do you check that the user can access a particular resource – when using Effective::DatatablesController ?

**Comment by matt-riemer** [comment]
I use CanCan for this

```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    can :index, User
    can [:edit, :update], User, id: user.id
    can :index, Suspension
    can [:index, :show], Applicant, user_id: user.id
end
```

**Comment by matt-riemer** [comment]
And I scope my collection to the right user, too I guess:

```ruby
    Thing.where(company_id: attributes[:company_id]).all
````

**Comment by Nerian** [comment]
I see. I too have all collections scoped to my client.

I was thinking more in the case that a user may manually construct a datatable and try to use it to query a datatable that is not supposed to have access to, even if the resource belongs to the same client, via Ajax. 

Let's say a member trying to query via Ajax a datatable that only an admin should have access too. In my case a user may have member and admin roles on different accounts. So is not like I can just check if the user is a member or admin. I need to check if the user is a member or admin of the particular account that he is querying about. He should not be able to list all members of an account, for example, if he is a member and not an admin. So I cannot check if the suer has access to a category of items, but to the item itself.

Perhaps I am being over zealous. I think that the user would need to mess with the cookie. Is that scenario possible?

**Comment by Nerian** [comment]
I just tried to replicate that scenario. I logged in as an admin and went to a page with a datatable that only a admin should be able to see. Then, in a different tab, I logged in as a member. A member should not be able to see the datatable. I tried making search – ajax query – on the admin table and I got a `Can't verify CSRF token authenticity`. So perhaps that scenario is not possible.

**Comment by matt-riemer** [comment]
Yea, if you messed with the cookie, it's possible you could somehow request the wrong data. (Unfortunately....) all the attributes are persisted in that cookie, and bounced back to the server.

BUT, the cookie is all super encrypted, so it's basically impossible to mess with those values

**Comment by Nerian** [comment]
Excellent, sounds good :)

Thanks!
