### ISSUE TITLE
Import css and js without require

### ISSUE THREAD

**Issue by MusinAmir** [code-and-effect/effective_datatables#63]
Hello. I'm using this gem to write plugin in redmine. Unfortunately i can't put require in application.js( application.css). I'm importing assets with stylesheet_link_tag, javascript_include_tag. Is it possible to import effective_datables assets same way? Thank you for your attention!

**Comment by matt-riemer** [comment]
I haven't used redmine....but there must be some way to put a file into your asset pipeline.

I think it's just adding that 1-liner to your `application.js` or `application.css` or whichever files you're using as your application javascript / stylesheet

**Comment by MusinAmir** [comment]
Unfortunately it didn't work

**Comment by danajanssen** [comment]
effective_datatables is intended to have it's assets included via the asset pipeline. if you're not using the asset pipeline then you'll need to copy the assets from the gem into your app directly and modify them to not use require:

https://github.com/code-and-effect/effective_datatables/tree/master/app/assets

**Comment by MusinAmir** [comment]
Yeah, i did that. It's work. Thank you!

**Comment by danajanssen** [comment]
great!
