### ISSUE TITLE
Page Length

### ISSUE THREAD

**Issue by Talha5** [code-and-effect/effective_datatables#65]
``` ruby
class DiscountsDatatable < Effective::Datatable
  datatable do
    length 5

    col :id
    col :title
    col :type

    actions_col
  end

  collection do
    Discount.all.order(created_at: :desc)
  end
end
```
I recieve: length must be 10, 25, 50, 100, 250, 500, :all. The docs state we can specify the length to be 5 as well. [length-link](https://github.com/code-and-effect/effective_datatables#length)

**Comment by matt-riemer** [comment]
Good catch @Talha5 !

I was tempted to update this with a PR that removes "5" docs. lol...

But instead, sure why not, upgrade effective_datatables to 3.3.9. It'll do the right thing with length 5.

Thanks!
