### ISSUE TITLE
Some issues with the filters

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#66]
Hi,

I have this filter:

```
filter :status, 'unarchived', as: :select, collection: [['Unarchived', 'unarchived'], ['Draft', 'draft'], ['Archived', 'archived'], ['Sent', 'sent'], ['Viewed', 'viewed'], ['Overdue', 'overdue']], label: false, include_blank: false
```

And this renders this:

<img width="606" alt="captura de pantalla 2018-01-14 a las 13 04 16" src="https://user-images.githubusercontent.com/259568/34915738-90e0af8a-f92b-11e7-883b-83c1e9d63090.png">

Problems:

1. The `label: false` is ignored. 
2. The default value ('unarchived') is used in the filters but it is not applied to the form; the `unarchived` is not selected in the `select`. 
3. `include_blank` is also ignored. 

What am I doing wrong? 😅

**Comment by Nerian** [comment]
I am also having trouble with this one:

```
filter :reports, nil, as: :grouped_select, collection: grouped_options_for_select(reports_collection), group_method: :last, label: false, include_blank: false


    def reports_collection
      [['Quarters', quarters], ['Months', months]]
    end

    def months
      (1..12).map {|m| [I18n.translate('date.month_names')[m], m]}
    end

    def quarters
      [['Q1', 'q1'], ['Q2', 'q2'] , ['Q3', 'q3'], ['Q4', 'q4']]
    end
```
That gives me an error.

<img width="1379" alt="captura de pantalla 2018-01-14 a las 13 59 10" src="https://user-images.githubusercontent.com/259568/34916129-23ab9f62-f933-11e7-83ad-8d3a612d4e24.png">

Notice the value of input_html:

`:input_html=>{:name=>"", :group_method=>:last, :include_blank=>false...`

So the option in the `filter` are being passed to `input_html`, when they should not.

I think this is the line that is causing the problem:

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/effective_datatable/dsl/filters.rb#L11

Maybe we could add `:group_method` and `:include_blank` to the list of named parameters for the `filter` method so that is not added to the `input_html`. That would fix problem 3 too.

Thoughts?

You would need to support these methods too: `group_method`, `group_label_method`, `value_method`, `label_method`.

**Comment by matt-riemer** [comment]
Hey @Nerian !

As you already pointed out, that `filters` command isn't merging any passed options.  Neither is the 

https://github.com/code-and-effect/effective_datatables/blob/master/app/helpers/effective_datatables_private_helper.rb#L33

Both those methods should probably be rewritten to accept arbitrary options. And do the params merge correctly. But that can be really tricky code to write sometimes. :/

I wanted to keep the ability for regular form inputs, as well as effective form inputs, to both work interchangeably in those methods. I'm not sure that it does! :)


Try using a hash for your effective_form_inputs grouped collection select.  {'Posts' => [], 'Users' => []} kinda thing.

I'm maxed out in January here, but I would be able to circle back to this on my next big project.  Cheers!
