### ISSUE TITLE
Q: integration with Yet Another DataTables Column Filter (yadcf), support of JSONB column data filtering

### ISSUE THREAD

**Issue by matissg** [code-and-effect/effective_datatables#70]
It seems you have created great gem and I'd like to try it. I was wondering, if it would be possible to integrate [Yet Another DataTables Column Filter (yadcf)](http://yadcf-showcase.appspot.com/server_side_source.html) with your gem?

In addition I'm interested, if your gem supports filtering / searching by JSONB column data? For example, in my `Position` model I have JSONB column `data` and I would like to search by values of `ptype` inside it. I can access my data with something like this: `Position.data->>'ptype'`

**Comment by matt-riemer** [comment]
Hey @matissg 

Great questions....

It's probably possible to integrate YADCF with the gem....Try just adding it into the app/assets/javascripts directory and test it out!

I have no built in support for JSONB column data. I don't usually work with that. But it should be easy enough to hook up...

You'd need to add it as a column type to effective_datatables, and then take a look at effective_resources gem where all the sorting/ordering is done.  Might not be too bad! ActiveRecord makes things easy :)

https://github.com/code-and-effect/effective_resources/blob/master/app/models/effective/resources/relation.rb
