### ISSUE TITLE
DataTable error: unable to find datatable

### ISSUE THREAD

**Issue by eleos** [code-and-effect/effective_datatables#71]
As of 3.2.1+ effective_datatables is unable to find the datatable for me. 

First load works. But reloading (filtering, refresh) gives:

DataTable error: unable to find datatable
Please refresh the page and try again

The url of the JSON request is: "/datatables/skype_users_datatable--40537094.json?locale=en"

Parameters: {"draw"=>"3", "columns"=>{"0"=>{"data"=>"0", "name"=>"display_name", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}, "1"=>{"data"=>"1", "name"=>"sign_in_address", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}, "2"=>{"data"=>"2", "name"=>"status", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}, "3"=>{"data"=>"3", "name"=>"phone", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}, "4"=>{"data"=>"4", "name"=>"office", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}, "5"=>{"data"=>"5", "name"=>"department", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}, "6"=>{"data"=>"6", "name"=>"_actions", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}, "visible"=>"true"}}, "order"=>{"0"=>{"column"=>"0", "dir"=>"asc"}}, "start"=>"0", "length"=>"25", "search"=>{"value"=>"", "regex"=>"false"}, "cookie"=>"-40537094", "locale"=>"en", "id"=>"skype_users_datatable--40537094"}

table:
<table class='effective-datatable table table-bordered table-striped' data-columns='[{&quot;name&quot;:&quot;display_name&quot;,&quot;title&quot;:&quot;\u003cspan class=\&quot;search-label\&quot;\u003eDisplay Name\u003c/span\u003e&quot;,&quot;className&quot;:&quot;col-string col-display_name&quot;,&quot;searchHtml&quot;:&quot;\u003cdiv class=\&quot;form-group form-md-line-input string optional datatable_search_display_name datatable_search\&quot;\u003e\u003cinput class=\&quot;form-control string optional\&quot; title=\&quot;Display Name\&quot; data-column-name=\&quot;display_name\&quot; data-column-index=\&quot;0\&quot; placeholder=\&quot;\&quot; type=\&quot;text\&quot; id=\&quot;datatable_search_display_name\&quot; /\u003e\u003c/div\u003e&quot;,&quot;responsivePriority&quot;:10000,&quot;search&quot;:null,&quot;sortable&quot;:true,&quot;visible&quot;:true},{&quot;name&quot;:&quot;sign_in_address&quot;,&quot;title&quot;:&quot;\u003cspan class=\&quot;search-label\&quot;\u003eSign In Address\u003c/span\u003e&quot;,&quot;className&quot;:&quot;col-string col-sign_in_address&quot;,&quot;searchHtml&quot;:&quot;\u003cdiv class=\&quot;form-group form-md-line-input string optional datatable_search_sign_in_address datatable_search\&quot;\u003e\u003cinput class=\&quot;form-control string optional\&quot; title=\&quot;Sign In Address\&quot; data-column-name=\&quot;sign_in_address\&quot; data-column-index=\&quot;1\&quot; placeholder=\&quot;\&quot; type=\&quot;text\&quot; id=\&quot;datatable_search_sign_in_address\&quot; /\u003e\u003c/div\u003e&quot;,&quot;responsivePriority&quot;:10000,&quot;search&quot;:null,&quot;sortable&quot;:true,&quot;visible&quot;:true},{&quot;name&quot;:&quot;status&quot;,&quot;title&quot;:&quot;\u003cspan class=\&quot;search-label\&quot;\u003eStatus\u003c/span\u003e&quot;,&quot;className&quot;:&quot;col-string col-status&quot;,&quot;searchHtml&quot;:null,&quot;responsivePriority&quot;:10000,&quot;search&quot;:null,&quot;sortable&quot;:false,&quot;visible&quot;:true},{&quot;name&quot;:&quot;phone&quot;,&quot;title&quot;:&quot;\u003cspan class=\&quot;search-label\&quot;\u003ePhone\u003c/span\u003e&quot;,&quot;className&quot;:&quot;col-string col-phone&quot;,&quot;searchHtml&quot;:null,&quot;responsivePriority&quot;:10000,&quot;search&quot;:null,&quot;sortable&quot;:false,&quot;visible&quot;:true},{&quot;name&quot;:&quot;office&quot;,&quot;title&quot;:&quot;\u003cspan class=\&quot;search-label\&quot;\u003eOffice\u003c/span\u003e&quot;,&quot;className&quot;:&quot;col-string col-office&quot;,&quot;searchHtml&quot;:null,&quot;responsivePriority&quot;:10000,&quot;search&quot;:null,&quot;sortable&quot;:true,&quot;visible&quot;:true},{&quot;name&quot;:&quot;department&quot;,&quot;title&quot;:&quot;\u003cspan class=\&quot;search-label\&quot;\u003eDepartment\u003c/span\u003e&quot;,&quot;className&quot;:&quot;col-string col-department&quot;,&quot;searchHtml&quot;:null,&quot;responsivePriority&quot;:10000,&quot;search&quot;:null,&quot;sortable&quot;:true,&quot;visible&quot;:true},{&quot;name&quot;:&quot;_actions&quot;,&quot;title&quot;:&quot;\u003cspan class=\&quot;search-label\&quot;\u003e\u003c/span\u003e&quot;,&quot;className&quot;:&quot;col-actions col-_actions&quot;,&quot;searchHtml&quot;:null,&quot;responsivePriority&quot;:5000,&quot;search&quot;:null,&quot;sortable&quot;:false,&quot;visible&quot;:true}]' data-cookie='-40537094' data-display-length='25' data-display-order='[0,&quot;asc&quot;]' data-display-records='13' data-display-start='0' data-input-js-options='{}' data-reset='&lt;a class=&quot;btn btn-default buttons-reset-search&quot; href=&quot;#&quot;&gt;
&lt;span&gt;Reset&lt;/span&gt;
&lt;/a&gt;
' data-simple='false' data-source='/datatables/skype_users_datatable--40537094.json?locale=en' data-total-records='13' id='skype_users_datatable--40537094'>
<thead>

**Comment by matt-riemer** [comment]
the `id` and `cookie` params are weird values here...

I would expect the ID to be like `skype_users_datatable-254525931356` (12 digits) and the cookie to be like like `637810618182` (12 digits) as well.

You are upgrading?  Maybe try clearing all cookies.  Sorry! :(

I do remember reworking all the cookie stuff in and around those verions.

FYI, here's where we turn the ID into a class. And where your error is coming from:

https://github.com/code-and-effect/effective_datatables/blob/master/app/controllers/effective/datatables_controller.rb#L23

**Comment by eleos** [comment]
Something seems to be wrong with generating the ID for the datatables. But when I modify the regex to 

      id = id.to_s.gsub(/-\d{9,12}\z/, '').gsub('-', '/')

it works again.

**Comment by matt-riemer** [comment]
Yea, adjusting the regex is totally reasonable. I wouldn't mind making that change...

I'm curious how your generated ID has two `-` characters and not the right number of digits tho.

Did you reset all your cookies? :)  Make sure tehre's no session `_effective_datatables_cookie` or any individual table ones...Something weird going on there

**Comment by KoenDierckx** [comment]
Hey Matt, we are running into this issue also.
I've traced it back to:
```
      def cookie_param
        [self.class, attributes].hash.to_s.last(12)
      end

```
For my debug session, [self.class, attributes].hash gives -299455564
This is correct, as the hash function returns a FixNum
[https://apidock.com/ruby/Fixnum](https://apidock.com/ruby/Fixnum)

So this explains the extra - symbol

**Comment by KoenDierckx** [comment]
#74

**Comment by matt-riemer** [comment]
Try effective_datatables 4.0.2 or 3.4.2 which both have this fix.  Cheers.
