### ISSUE TITLE
Table are saving the state from previous request

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#76]
Hi!

I noticed that when I change a filter and then wander to another page, and then I come back to the original page, the table will be set up with the changed filter. I would expect it to be pristine; without any filters.

Is there a way to configure this?

It is problematic in my case because one of the filters is a date.

```ruby
    filters do
      filter :date, I18n.localize(Time.current, format: I18n.t('datepicker.dformat', default: '%d/%m/%Y')), as: :date_picker, label: false, parse: lambda { |term| Time.zone.parse(term).to_date }
    end
```

So with this, the date will be initialised to today. Then the user can change it to some other day. When the user goes to another page, and then comes back, the datatable **uses** the second date, not the default one; but strangely the datepicker is initialised with the default one. It is very confusing.

Same thing happens with sorting, and column filters. I would prefer to have a pristine table every-time it is rendered. 

Is it posible?

I have got this in my main.js file  

```
$.extend( true, $.fn.dataTable.defaults, { destroy: true, stateSave: false } );
```

But doesn't seem to be a problem of stateSave. I am guessing this is saved in the cookie.

Thoughts?

**Comment by matt-riemer** [comment]
Yep, this is supposed to be a feature! :)

The datatables cookie stores the filters, search, sort, length, pagination, attributes etc options for the last (<4kb of cookie storage) ~10 tables.

And loads that state from the cookie when a user returns to a page with that table.

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/effective_datatable/state.rb#L90

This gem has been doing this for a long time!  It's not new...

What branch of effective_datatables are you going to be using? sticking with bootstrap3 and 3.x yea?

This cookie state could be turned into a config option.  Figure this should be table specific, or a global option?

Cheers

**Comment by Nerian** [comment]
I am using the bootstrap3 one, yes.

A global option would work for me.

Thanks!

**Comment by matt-riemer** [comment]
Your wish is my command

Successfully registered gem: effective_datatables (3.4.3)

Add `config.save_state = false` to your `config/initializers/effective_datatables.rb` and it will no longer use the cookie to load state.

Have a good one :)

**Comment by Nerian** [comment]
You are the best :)

Working perfectly well

Thanks!
