### ISSUE TITLE
issue with searching sorting  when using it with nested attributes

### ISSUE THREAD

**Issue by uzaif313** [code-and-effect/effective_datatables#77]
when  i used datables gem with single resource its work flawlessly :fire: 
but when i switch to display table based on parent records then its causing issue with searching and sorting
from little knowledge of rails i came to know that this happen because when i perform sorting and searching at that time parent_id is not passed

eg 

i have `menu type` model which contain `menu_items` so i am displaying menu_items based on menu_types

below are my `data tables` class

```
class Admin::MenuItemDatatable < Effective::Datatable
  datatable do
    col :name
    col :description
    col :image, sort:false, search: false do |data|
     content_tag(:div,image_tag(data.image.url(:thumb)))
    end
    col :status
    col :created_at
    order :created_at, :desc
    actions_col
  end

  collection do
    MenuItem.where(menu_type_id:params[:menu_type_id])
  end
end
```

Let me know if you need anything else

**Comment by matt-riemer** [comment]
What is the value of params[:menu_type_id] maybe this should be attributes[:menu_type_id] when you initialize your datatable with `@datatable = Admin::MenuDatatable.new(menu_type_id: 3)`

**Comment by uzaif313** [comment]
This way i create object of datatable class `@datatable = Admin::MenuDatatable.new(self)`

**Comment by uzaif313** [comment]
Thanks, @matt-riemer  resolved via passing 
in controller
`@datatable = Admin::MenuDatatable.new(self,menu_type_id:params[menu_type_id])`
in datatable 
`Menu.where(menu_category_id:attributes[:menu_type_id])`
