### ISSUE TITLE
On delete (destroy) no refresh?

### ISSUE THREAD

**Issue by rbosch** [code-and-effect/effective_datatables#78]
When I click the delete icon, I get a nice dialog for confirmation. After confirming (click Yes), the record is still visible in the table. I need to click the refresh button to update the table.

Anyway to call automatically call a refresh or activate a update of the table when clicking a action / delete ?

Thanks!

**Comment by matt-riemer** [comment]
Hey @rbosch 

That's a weird one!

The delete confirmation is provided by rails-ujs, and I would expect the entire page to refresh after it's clicked.  It's just a normal delete action, that redirects back to the current page.

Do you have some kind of javascript errors going on?  Check the console?

What version of datatables are you running?  

I think you must have the `jquery_ujs` gem already installed and working if you're seeing that confirmation dialog in the first place.

**Comment by rbosch** [comment]
Hi @matt-riemer,

> It's just a normal delete action, that redirects back to the current page.

Aha, that was the issue. I was not doing that in my destroy.

I'm the DT in a master/detail. Anyway easy way to implement the destroy as a Ajax call (hook?)?

Thanks!

**Comment by matt-riemer** [comment]
No, implementing the destroy as an ajax call is not super easy -- probably ~5 hours of work.

I want this feature too! 

...I may have budget to do this in an upcoming client app of mine.  :)

One day I'm hoping to be able to implement a full New/Edit/Destroy crud workflow right inside the datatable without leaving the page -- a mini full page application -- but the rails way!.    We'll see...

Thanks :)
