### ISSUE TITLE
belongs_to column with nil values

### ISSUE THREAD

**Issue by holgum** [code-and-effect/effective_datatables#82]
Having some issues with related column (belongs_to) where (unfortunately) there are nils.
Started with:
```ruby
  col  group, action: show, sort: true
```
But unexpectedly, the records with the nils in the group column always show at the end of the table, regardless of whether I ascending or descending arrows are clicked. Users will undoubtedly find that very confusing.  What do you recommend? I turned it into a 'val' column but this seems like it would be a common case so I thought I would ask.

Also (and this is probably more of an edge case) this application does not run under the root context, and the links that get generated for the related column above do not include the context that is set by 'config.relative_url_root'.

Using 3.x gem.

**Comment by matt-riemer** [comment]
Hey @holgum 

Yea, great question.

I thought that the nulls were being sorted correctly, FIRST or LAST with ASC or DESC depending.

But maybe I've only tested this thoroughly with postgres database.  Are you on postgres?

The searching / sorting for belongs_to columns is fairly complex.  We use the effective_resources gem to look at the belongs_to class -- figure out what to_s column probably represents that belongs_to, something like `name` or `title` -- then find the natural order of those objects, translate that back to some custom sorted IDs, and finally sort by that back in datatables.

Maybe it's overkill?  But my implementation is better than just ordering by ID.

You can check out the sorting code here:

https://github.com/code-and-effect/effective_datatables/blob/master/app/models/effective/datatable_column_tool.rb#L42

Here, `order_column` is called, and usually delegates to Effective::Resources. Which ends up calling:

https://github.com/code-and-effect/effective_resources/blob/master/app/models/effective/resources/relation.rb#L12

(Hey, I just noticed...comapre that `relation.rb` line 25 vs 43 -- maybe that's the fix right there.


If you can't find what you're looking for here, you can always do a custom order on that column yourself:

https://github.com/code-and-effect/effective_datatables/tree/bootstrap3#advanced-search-and-sort


Cheers

**Comment by holgum** [comment]
Yes, we are using Postgres.
Also have a 'to_s' method on the related 'Group' model that just returns the name. If that is commented out we get the object ID's of the groups in the default column search dropdown instead of the names.  
Probably not relevant(?) but we are using JRuby 9.1.13.

I will try and work thru the code when I have more time. Day job interfering.
Thanks!
