### ISSUE TITLE
Is it possible to not show column header filters?

### ISSUE THREAD

**Issue by zuyderleven** [code-and-effect/effective_datatables#83]
I would like to have single filter field filtering multiple columns and not show the column header filters above each column. Anybody a solution?

Regards, Joris

**Comment by zuyderleven** [comment]
Found the answer :-) It's in the Bootstrap 4 manual and not in the BS3 
```ruby
   col :id, search: false
   col :sterrelatie, search: false
   col :customer_type, search: false
   col :naam, search: false
   col :adres, search: false
   col :postcode , search: false    
   col :woonplaats  , search: false
   col :email, search: false
   col :telefoon, search: false
```

**Comment by matt-riemer** [comment]
Aaah good catch

Just curious, are you using this gem with BS4 or BS3? :)

Hope this gem helps your day.  Cheers.
