### ISSUE TITLE
How to add separate search input which searches/filters multiple columns

### ISSUE THREAD

**Issue by zuyderleven** [code-and-effect/effective_datatables#84]
I don't find it handy to have these filtercolumns above each column. I would rather like to have a 1 separate input which filters on typing in multiple columns. Can somebody give me a hint in how to create such functionality?

Regards, Joris

**Comment by matt-riemer** [comment]
This gem is really built around the one search & sort per column type design. But you could probably work around it:

1. Use search: false on each column, or css, to hide the column specific search inputs
2. Use the `filters` dsl to create a single search input
3. In your `collection do` you can consider the `filters[:your_filter_field]` and implement all search and/or sorting yourself.

Good luck! :)
