### ISSUE TITLE
i18N

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#85]
Hi,

I was wondering if there is support for I18n.

Specifically, I was thinking that it would be great if columns by default looked for a translation.

For example:

```
  col :name
```

That would look for  `en.effective_datatables.name`. 

Thoughts?

**Comment by matt-riemer** [comment]
I think it's a good idea!

I haven't had much experience with internationalization, but I like the idea of this :)

**Comment by Nerian** [comment]
Here is how SimpleForm is doing it:

https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/inputs/base.rb#L174

**Comment by matt-riemer** [comment]
I still like this idea, but it's too big of a project. I'd probably never start it. I'm a spoiled north american that only has to deal with english :)

**Comment by Nerian** [comment]
Haha :)  At some point I will have to explain why my app is all translated, except for those pesky tables. I would just blame the Americans 🤣 

I don't think it should too complicated to add support it. Would accept a PR?

**Comment by matt-riemer** [comment]
Yea, If you do the work I'll accept it :)

Gimme PR! Thanks hehe
