### ISSUE TITLE
grouped_select in 4.*

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#86]
Hi,

I am upgrading to effective_datatables 4.*  and I have run into an issue.

The `grouped_select` doesn't seem to work. I just renders a regular input. This is what I get when using the readme example:

```
filter :reports, '2018', as: :grouped_select, collection: [['Years', [['2017', '2017'], ['2018', '2018']]], ['Months', [['January', '1'], ['February', '2']]]], group_method: :last
```

That gives me:
```
<div class="form-group col-auto">
    <input class="form-control" group_method="last" value="2018" name="" placeholder="Reports" autocomplete="off" type="text">
</div>
```

I have got this settings:

```scss
@import "effective_datatables";
@import 'effective_bootstrap';
```

application.js
```
//= require effective_datatables
//= require effective_select/input        <- I don't use the whole effective_bootstrap
```

This used to work in branch 3.*.   Any idea of what could be wrong?

**Comment by matt-riemer** [comment]
try passing multiple: true maybe!

**Comment by Nerian** [comment]
Passing `multiple: true` has no effect. It still shows a regular input field.

`multiple` is for a multiple select, isn't? It is not what I want to get. I just want a `grouped_select` :)

This is what I used to get:

<img width="550" alt="captura de pantalla 2018-10-04 a las 9 03 39" src="https://user-images.githubusercontent.com/259568/46457969-7b365880-c7b4-11e8-8d0f-76fde4b153d9.png">

**Comment by Nerian** [comment]
I found the way to do it now:

```
filter :reports, '2018', as: :select, collection: {'Years' => [['2017', '2017'], ['2018', '2018']], 'Months' => [['January', '1'], ['February', '2']]}, group_method: :last, grouped: true
```

So `select` instead of `grouped_select`, `grouped: true` and the collection needs to be an hash, not an array.

I wonder if this code could be changed:

https://github.com/code-and-effect/effective_datatables/blob/f8207054d708bf3da0cab1d70e4f8abef6f8f85d/app/helpers/effective_datatables_private_helper.rb#L119

Because before I could use any of simple_form's input types. Now it is going to default to `text_field`. 

I am not sure how it used to work. Is this the code that was used for filters?

https://github.com/code-and-effect/effective_datatables/blob/bootstrap3/app/helpers/effective_datatables_private_helper.rb#L33

**Comment by matt-riemer** [comment]
Yea, this code could probably be improved upon to merge passed attributes better.

https://github.com/code-and-effect/effective_datatables/blob/master/app/helpers/effective_datatables_private_helper.rb#L37

**Comment by matt-riemer** [comment]
I updated the README to match

`filter :year_group, '2018', as: :select, grouped: true, collection: { 'Years' => [['2017', 2017], ['2018', 2018]], 'Months' => [['January', 1], ['February', 2]] }`

Cheers

**Comment by Nerian** [comment]
Excellent, thanks!
