### ISSUE TITLE
include_blank is ignored

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#87]
Hi,

The include_blank option is ignored.

```
filter :year, 2018, as: :select, collection: [2018, 2017], include_blank: false
```

That still allow to remove selection.

**Comment by matt-riemer** [comment]
The include_blank IS being passed down to the select.

**Comment by Nerian** [comment]
That's correct. The `include_blank` option is passed down.

But the `select` stills allows to clear selection:

<img width="100" alt="captura de pantalla 2018-10-22 a las 18 28 02" src="https://user-images.githubusercontent.com/259568/47304909-3ae62f80-d628-11e8-9b09-4ea8a1b9b47f.png">

If you click on the X the input is cleared; so it does allow a blank. That behaviour is executed by Select2.

https://github.com/code-and-effect/effective_bootstrap/blob/master/app/models/effective/form_inputs/select.rb#L36

Is that line, `allowClear` is set to true unless if it is a multiple option select.

I can force allowClear false by doing this:

```
filter :year, Time.current.year, as: :select, collection: year_collection, include_blank: false, input_js: { allowClear: false }
```

But perhaps `allowClear: false` could be the default if `include_blank` is set to false. After all, if you do not include blank, why would you allow a clear?

Thoughts?

**Comment by matt-riemer** [comment]
This has been completed.

Adding `include_blank: false` will automatically set `allowClear: false` too.

effective_bootstrap 0.2.3

Cheers :)

**Comment by Nerian** [comment]
Perfecto :)

Thanks!
