### ISSUE TITLE
Optionally disable collapsing columns

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#89]
Hello,

With Bootstrap 4 there is some support for responsive tables. I was wondering if it is possible to disable the behaviour of columns automatically collapsing; this way it will just use bootstrap's solution.

Thanks.

**Comment by matt-riemer** [comment]
Hey @Nerian  :)

I've been watching these issues, thanks for bringing all this stuff up!

I will chip away at things as I have time, been too busy lately tho :)

You could pass `responsive: false` to the second argument of render_datatable. I haven't tested but should work ;)

**Comment by Nerian** [comment]
Cool. Thanks!

```
= render_datatable(@contacts_table, input_js: { responsive: false })
```

That worked :)

**Comment by matt-riemer** [comment]
Nice, that's a small win :)

Hey, as an experiment try using `render_inline_datatable` on one of your simple crud tables.

I'm building out inline Edit/new screens, delete actions, etc, might be of use to you...!

**Comment by Nerian** [comment]
Cool, looking forward to it :)
