### ISSUE TITLE
Inline Crud

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#91]
Hi,

I have got a `data-remote` link in the actions of an effective-datatable. When the user clicks on this button, a request is made and the result is rendered into a modal. The modal contains a form. When the user clicks on the "Done" button on the form, it goes back to the table.

The behaviour is kind of broken now. When the user clicks on the button, the table is put on a "Loading" state. And when the user clicks on the "Done" button the user is redirected to some page; that it shouldn't.

I tracked it down to this:

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/inline_crud.js.coffee#L5

It's the Inline CRUD you are working on. The code is listening for any ajax event inside the table.

Perhaps we could make the listener more specific? 

```
$(document).on 'ajax:beforeSend', '.dataTables_wrapper your_custom_crud_buttons', (e, xhr, settings)
```

Thoughts?

**Comment by matt-riemer** [comment]
Are you using some kind of AJAX from within your table as well?  


`$(document).on 'ajax:beforeSend', '.dataTables_wrapper', (e, xhr, settings) ->`

The selector could be changed to scope the `.col-actions`  and maybe include an opt out. Something like

`.datataTables_wrapper .col-actions:not(.ignore-effective-datatables-ajax)`

Is that selector doing the wrong thing for you

**Comment by matt-riemer** [comment]
Is the .col-actions enough? Cheers.

**Comment by Nerian** [comment]
I think that could work:

`.datataTables_wrapper .col-actions:not(.ignore-effective-datatables-ajax)`

But I think it would be better if instead of opt out it were out by default. 

Couldn't you simple wrap the effective CRUD actions with `.effective-crud`?

Also, I think you listen for `effective-datatables-inline-row` too. So:

```
$(document).on 'ajax:beforeSend', '.datataTables_wrapper .col-actions .effective-crud, .datataTables_wrapper .effective-datatables-inline-row', (e, xhr, settings) ->


$(document).on 'ajax:success', '.datataTables_wrapper .col-actions .effective-crud, .datataTables_wrapper .effective-datatables-inline-row', (e) ->


```

**Comment by matt-riemer** [comment]
Hey, I think I have fixed this!

1. I am only looking for data-remote events in the .col-actions, instead of the entire datatable.

2. When using effective_resource and `render_resource_actions` under the hood, all appropriate links are `data-remote`, and therefore hijacked by datatables inline ajax.

You can now disable this by calling `actions_col(inline: false)` to never make those links data-remote in the first place.

3. You can add `data-inline: false` to any links, to totally disable the hijack behaviour.

**Comment by matt-riemer** [comment]
https://github.com/code-and-effect/effective_datatables/commit/07e6a5b125a78aa669c7bd6b5ff08c64fb5bba22

**Comment by Nerian** [comment]
Hi,

I used `data-inline: false` for my JS link and it solved the conflict. Perfect :)

Thanks
