### ISSUE TITLE
Search option not working.

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_datatables#93]
Hi,

With the new version there is a default search input. I am not going to use it for now so I tried disabling it like this:

```
= render_datatable(@invoices_table, search: false)
```

https://github.com/code-and-effect/effective_datatables/commit/51c42b01c96fc1f536a9e7e29918eb2723a7346f#diff-be0e9f834e571279202f881caffd29b6R23

There I see that the search input would still be there, but the intention is that the `hide-search` will be added and it will consequently hide the search input. But this will not happen because the `hide-search` class is being added to the `table` element and the searchn input is actually inside the `effective-datatables-filters` element. 

Maybe the search param needs to be passed to the `render_datatable_filters` call, here:

https://github.com/code-and-effect/effective_datatables/blob/51c42b01c96fc1f536a9e7e29918eb2723a7346f/app/helpers/effective_datatables_helper.rb#L70

Thoughts?

**Comment by matt-riemer** [comment]
To me, these are two separate elements

1. the Filters / Scopes form.  Which can now be enabled or disabled with `render_datatable(datatable, filters: false)`.

and

2. the Search fields in the table thead.  These are `search: false`.


I've been adding good stuff to datatables.  All the `Blank (null)` search for NULLS was really needed imho!

**Comment by Nerian** [comment]
Ohh I see. The `search: false` does remove the ones in the table. I wanted to remove the one that is now in the filters.

Photo:

<img width="1277" alt="captura de pantalla 2018-11-01 a las 18 26 07" src="https://user-images.githubusercontent.com/259568/47868086-9fad4100-de03-11e8-85ab-92608ece0270.png">

I meant the search box in the top right corner. Is there a way to remove that one?

**Comment by matt-riemer** [comment]
Oh weird, I've never seen that Search box in the corner before!

**Comment by Nerian** [comment]
I checked prior version and it doesn't show the search box. It's appearing only on 4.3.7

**Comment by Nerian** [comment]
This is version 4.3.6:

<img width="1510" alt="captura de pantalla 2018-11-02 a las 11 39 16" src="https://user-images.githubusercontent.com/259568/47910734-08dc9500-de94-11e8-8e74-b83e7fba8dd3.png">

This is version 4.3.7

<img width="1510" alt="captura de pantalla 2018-11-02 a las 11 38 42" src="https://user-images.githubusercontent.com/259568/47910748-109c3980-de94-11e8-8d8b-56f44f8b73de.png">


Notice the Search box and also **length pagination controls** at the top of the page instead of at the bottom.


Could this change be the culprit?

https://github.com/code-and-effect/effective_datatables/commit/51c42b01c96fc1f536a9e7e29918eb2723a7346f#diff-7e5212f9b4e1a219878a7a239f2afbb1L52

**Comment by matt-riemer** [comment]
Yea...I think I see whats up here.

Are you overriding the `input_js` or `input_js[:dom]` option at all?

I wanted to make every part of the table more configurable, so I removed the hardcoded `dom` javascript option, and build it, and pass it at runtime, here:

https://github.com/code-and-effect/effective_datatables/commit/51c42b01c96fc1f536a9e7e29918eb2723a7346f#diff-be0e9f834e571279202f881caffd29b6R29

Is it not getting passed to your datatable?

I bet the dom option is nil or something, and the datatable is going back to defaults somewhere.

DId you try just deleting your entire apps `/tmp` folder? Sometimes that fixes strange issues for me :)

**Comment by matt-riemer** [comment]
Sorry for the bad upgrade path here...

I really try to follow the https://semver.org/ philosophy

Given a version number MAJOR.MINOR.PATCH, increment the:

    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards-compatible manner, and
    PATCH version when you make backwards-compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.



I thought this was just a backwards-compatible change.  Maybe it shoulda been a MINOR bump hehe.

**Comment by Nerian** [comment]
The photo examples are from the example app:

https://github.com/Nerian/effective-datatables-example

It's as barebones as it gets. No custom anything.

**Comment by Nerian** [comment]
Ah I see the error:

https://github.com/code-and-effect/effective_datatables/commit/51c42b01c96fc1f536a9e7e29918eb2723a7346f#diff-be0e9f834e571279202f881caffd29b6R4

There you initialize `input_js` with `{}`.

There you initialize `input_js` if it has not been initialized.

https://github.com/code-and-effect/effective_datatables/commit/51c42b01c96fc1f536a9e7e29918eb2723a7346f#diff-be0e9f834e571279202f881caffd29b6R30

But {} is evaluated as true, so that's why it is empty.

**Comment by matt-riemer** [comment]
Nah, it's definitely assigning the `input_js[:dom]` for meeee! :)

Maybe this is a ruby version issue, I could change that param to be `nil` and then assign a {} otherwise

**Comment by Nerian** [comment]
Weird :)

I am running 2.5.1p57 and 2.5.3p105

**Comment by Nerian** [comment]
So if you run https://github.com/Nerian/effective-datatables-example  you don't get the search box?

**Comment by matt-riemer** [comment]
digging into this now.

**Comment by matt-riemer** [comment]
I can reproduce the issue when I switch out my `hamlit-rails` gem for `haml-rails`

Looks like this is some kind of json encoding issue problem!

**Comment by matt-riemer** [comment]
Okay, this has been resolved.

Checkout 4.3.8.  It's a good version. 

Thank you @Nerian so much for providing that demo app and pointing out this issue.

Removing a `.html_safe` seems to have fixed the issue.

**Comment by matt-riemer** [comment]
https://github.com/code-and-effect/effective_datatables/commit/8520b3fb485ed020c823319ddc7d9eb2f0030f04

**Comment by matt-riemer** [comment]
The input_js options parsing must have been busted all along...except it never mattered unto now when I started to use the `dom` input.  Doh!

**Comment by Nerian** [comment]
Awesome! Good job :)

**Comment by Nerian** [comment]
Good job tracking this down :)
