### ISSUE TITLE
please example with pagination for this gem

### ISSUE THREAD

**Issue by schekin** [code-and-effect/effective_datatables#94]
please example with pagination for this gem

**Comment by matt-riemer** [comment]
It should be pagination on by default!

The only way to disable pagination would be to call `render_datatable(@datatable, pagination: false)`

**Comment by matt-riemer** [comment]
But all the pagination does is show the pagination widget in the bottom right corner.

If you have bootstrap4 installed (or bootstrap3, if you're using that branch of this gem) it should be displayed

**Comment by schekin** [comment]
Thanks for the help! The problem was solved by installing CanCan. 

This  gem 'effective_datatables' is super! I have been looking for such a solution for a long time.
