### ISSUE TITLE
pass collection from controller to datatable  class

### ISSUE THREAD

**Issue by uzaif313** [code-and-effect/effective_datatables#99]
I dont know this feature is available or not in effective datatable. i have authorize logic  in controller and i want to pass collection from controller to datatable. it is possible 

```ruby
  collection = authorize User.all
  @datatable = UserDatatable.new collection
````

i have also issue with below image
![image](https://user-images.githubusercontent.com/16485731/49783926-8a4ffe80-fd41-11e8-9862-f78dafa5d88b.png)

**Comment by matt-riemer** [comment]
Hey uzaif313!

No, you can't pass a whole collection into the datatable, but you can do all your authorization from within the datatable class itself

```
collection do
   current_user.is?(:admin) ? User.all : User.all.where(client_id: current_user.client_id)
end
```

I bet you can also call `authorize` directly from within that `collection do ... end` block.


As for that screenshot, it looks like the javascript has initialized twice.  This really shouldn't be possible, as we use a `.initialized` guard class to prevent initializing twice. But, I dunno :)

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/initialize.js.coffee#L2

https://github.com/code-and-effect/effective_datatables/blob/master/app/assets/javascripts/effective_datatables/initialize.js.coffee#L177

**Comment by uzaif313** [comment]
@matt-riemer  Thanks for response man,
I am worried about dual initialized issue.

**Comment by matt-riemer** [comment]
I bet it's a turbolinks issue? :)
